<?php

/**
 * @file
 * Install, update and uninstall functions for the openy_prgf_3с feature.
 */

/**
 * Change view mode to full for 3-column paragraph.
 */
function openy_prgf_3c_update_8001() {
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory(drupal_get_path('module', 'openy_prgf_3c') . '/config/install');
  $config_importer->importConfigs(
    [
      'core.entity_view_display.paragraph.3c.default',
    ]
  );
}

/**
 * Add field_prfg_display_line_above.
 */
function openy_prgf_3c_update_8002() {
  // @see openy_prgf_4c_update_8001().
}
