<?php

/**
 * @file
 * Install, update and uninstall functions for the openy_prgf_3с feature.
 */

/**
 * Implements hook_uninstall().
 */
function openy_prgf_3c_uninstall() {
  \Drupal::service('openy.modules_manager')
    ->removeEntityBundle('paragraph', 'paragraphs_type', '3c');
  \Drupal::configFactory()
    ->getEditable('language.content_settings.paragraph.3c')
    ->delete();
}

/**
 * Change view mode to full for 3-column paragraph.
 */
function openy_prgf_3c_update_8001() {
  // Update is empty due to decoupling from provisioned website. Update was inherited and released. Should stay empty.
}

/**
 * Add field_prfg_display_line_above.
 */
function openy_prgf_3c_update_8002() {
  // Update is empty due to decoupling from provisioned website. Update was inherited and released. Should stay empty.
}
