<?php

/**
 * @file
 * Hooks and routines for the openy_update module.
 */

/**
 * Endpoint to check OpenY packages.
 */
define('OPENY_UPDATE_PACKAGES_ENDPOINT', 'http://openy.org:1880/packages');

/**
 * Get list of projects from the endpoint.
 *
 * @param array $projects
 *   Default value.
 */
function openy_update_get_projects(&$projects) {
  $client = \Drupal::httpClient();

  try {
    $response = $client->post(OPENY_UPDATE_PACKAGES_ENDPOINT, [
      'body' => json_encode($projects),
      'connect_timeout' => 10,
      'read_timeout' => 20,
      'timeout' => 30
    ]);
    if ($response->getStatusCode() == 200) {
      $body = $response->getBody();
      $body = $body->getContents();
      $projects = json_decode($body, TRUE);
    }
  }
  catch (\Exception $e) {
    \Drupal::logger('openy_update')->warning('Failed to connect to %endpoint', ['%endpoint' => OPENY_UPDATE_PACKAGES_ENDPOINT]);
  }
}

/**
 * Implements hook_update_status_alter().
 */
function openy_update_update_status_alter(&$projects) {
  openy_update_get_projects($projects);
}

/**
 * Implements hook_update_projects_alter().
 */
function openy_update_update_projects_alter(&$projects) {
  openy_update_get_projects($projects);
}
