<?php

/**
 * @file
 * Contains yptf_master specific functions.
 */

use Drupal\ymca_mappings\Entity\Mapping;
use Drupal\Core\Datetime\DrupalDateTime;

/**
 * Update/Populate "Personify Product" mappings.
 */
function yptf_master_product_updates_april_2017() {
  // Read CSV file with map.
  $path = drupal_get_path('module', 'yptf_master');
  $csv_file = $path . '/misc/PROD_PT_products_for_import_2017.csv';
  $map = array_map('str_getcsv', file($csv_file));

  foreach ($map as $product) {
    $product_code = $product[4];
    $product_code_array = explode('_', $product_code); //todo

    $data = [
      'type' => 'personify_product',
      'field_productid' => $product[1],
      'field_member_price' => $product[12],
      'field_nonmember_price' => $product[13],
      'field_package' => 1,
      'field_product_code' => $product[4],
      'field_product_code_nonm' => $product[5],
      'field_session_length' => 30,
    ];
    $mapping_repository = \Drupal::service('ymca_mappings.location_repository');
    $mapping = $mapping_repository->findByProductId($product[1]);
    $mapping = is_array($mapping) ? reset($mapping) : $mapping;
    if ($mapping && $mapping->hasField('field_location_ref')) {
      $location_id = $mapping->field_location_ref->getValue()[0]['target_id'];
      $data['field_location_ref'] = $location_id;
    }

    $mapping = Mapping::create($data);
    $mapping->setName($product[6]);
    $mapping->save();
  }
}

