<?php

/**
 * @file
 * Module file.
 */

/**
 * Run GroupEx Pro Form cache warmer.
 *
 * @param int $lock_lifetime
 *   Lock lifetime. 7 hours by default.
 */
function groupex_form_cache_warm($lock_lifetime = 25200) {
  $lock_name = "groupex_form_cache_warmer";

  // 7 hours of lock lifetime.
  $lock = \Drupal::lock();
  if ($lock->acquire($lock_name, $lock_lifetime)) {
    \Drupal::service('groupex_form_cache.warmer')->warm();
    $lock->release($lock_name);
  }
  else {
    $msg = 'Lock "%name" is still working. Exit.';
    Drupal::logger('groupex_form_cache')->info(
      $msg,
      [
        '%name' => $lock_name,
      ]
    );
  }
}

/**
 * Reset all GroupEx form cache.
 */
function groupex_form_cache_reset_all() {
  \Drupal::service("groupex_form_cache.manager")->resetCache(100);
}

/**
 * Quick GroupEx Pro cache reset (using TRUNCATE).
 */
function groupex_form_cache_reset_all_quick() {
  \Drupal::service("groupex_form_cache.manager")->quickResetCache();
}
