<?php

/**
 * @file
 * OpenY digital signage block time module.
 */

/**
 * Implements hook_theme().
 */
function openy_digital_signage_block_time_theme($existing, $type, $theme, $path) {
  return [
    'openy_digital_signage_block_time' => [
      'template' => 'openy-digital-signage-block-time',
      'variables' => [
        'wrapper_attributes' => NULL,
        'current_time' => NULL,
      ],
    ],
  ];
}
