<?php

/**
 * @file
 * Install, update and uninstall functions for the openy_prgf_timeline feature.
 */

/**
 * Update Timeline view to display human readable date.
 */
function openy_prgf_timeline_update_8001() {
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory(drupal_get_path('module', 'openy_prgf_timeline') . '/config/install');
  $config_importer->importConfigs(
    [
      'views.view.timeline',
    ]
  );
}
