<?php

/**
 * @file
 * Install, update and uninstall functions for the openy_prgf_3с feature.
 */

/**
 * Implements hook_update_dependencies().
 */
function openy_prgf_3c_update_dependencies() {
  $dependencies['openy_prgf_3c'] = [
    8003 => [
      'openy' => 8060,
    ],
  ];

  return $dependencies;
}

/**
 * Change view mode to full for 3-column paragraph.
 */
function openy_prgf_3c_update_8001() {
  // Update is empty due to decoupling from provisioned website. Update was inherited and released. Should stay empty.
}

/**
 * Add field_prfg_display_line_above.
 */
function openy_prgf_3c_update_8002() {
  // Update is empty due to decoupling from provisioned website. Update was inherited and released. Should stay empty.
}

/**
 * Update configs of the entity reference fields.
 */
function openy_prgf_3c_update_8003() {
  $config_dir = drupal_get_path('module', 'openy_prgf_3c') . '/config/install';
  $config_importer = \Drupal::service('openy_upgrade_tool.importer');
  $config_importer->setDirectory($config_dir);
  $config_importer->importConfigs([
    'field.field.paragraph.3c.field_prgf_3c_center',
    'field.field.paragraph.3c.field_prgf_3c_left',
    'field.field.paragraph.3c.field_prgf_3c_right',
    'paragraphs.paragraphs_type.3c',
  ]);
}
