<?php

/**
 * @file
 * Contains ymca_alters.module.
 */

define('MEMBERSHIP_BLOCK_ID', '1136');

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ymca_alters_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ymca_alters module.
    case 'help.page.ymca_alters':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Performs specific alters of default Drupal behavior') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function ymca_alters_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Rename 'Save and Publish' button everywhere.
  $bundles = ['article', 'camp', 'location', 'blog'];
  foreach ($bundles as $bundle) {
    if (
      $form_id == sprintf('node_%s_edit_form', $bundle) ||
      $form_id == sprintf('node_%s_form', $bundle)) {
      $form['actions']['publish']['#value'] = t('Save');
    }
  }

  // Adjust header image/button for pages.
  if (in_array($form_id, ['node_article_form', 'node_article_edit_form'])) {
    $form['field_header_image']['#states'] = [
      'visible' => [
        ':input[name="field_header_variant"]' => [
          ['value' => 'image'],
          ['value' => 'slideshow'],
        ],
      ],
    ];
    $form['field_header_button']['#states'] = [
      'visible' => [
        ':input[name="field_header_variant"]' => [
          ['value' => 'button'],
          ['value' => 'slideshow'],
        ],
      ],
    ];
  }
  if ($form_id == 'node_location_edit_form') {
    $edit_link_url = \Drupal\Core\Url::fromUri('internal:/block/' . MEMBERSHIP_BLOCK_ID);
    $edit_link_url->setOption('attributes', array('target' => '_blank'));
    /* @var \Drupal\Core\Link $edit_link */
    $edit_link = new \Drupal\Core\Link('Edit Membership block', $edit_link_url);
    $form['field_membership_block']['#suffix'] = render($edit_link->toRenderable());
  }
}
