<?php

/**
 * @file
 * Hook implementations of the Scheduler API Test module.
 */

use Drupal\node\Entity\Node;

/**
 * Implements hook_scheduler_nid_list().
 */
function scheduler_api_test_scheduler_nid_list($action) {
  $nids = [];

  // Check to see what test nodes exist.
  $query = \Drupal::entityQuery('node');
  $nodes = Node::loadMultiple($query->execute());

  foreach ($nodes as $nid => $node) {
    // If publishing and this is the publish test node, set a date and add
    // the node id to the list.
    if ($action == 'publish' && $node->title->value == 'API TEST nid_list publish me') {
      $node->set('publish_on', REQUEST_TIME)->save();
      $nids[] = $nid;
    }
    // If unpublishing and this is the unpublish test node, set a date and add
    // the node id to the list.
    if ($action == 'unpublish' && $node->title->value == 'API TEST nid_list unpublish me') {
      $node->set('unpublish_on', REQUEST_TIME)->save();
      $nids[] = $nid;
    }
  }
  return $nids;
}

/**
 * Implements hook_scheduler_nid_list_alter().
 */
function scheduler_api_test_scheduler_nid_list_alter(&$nids, $action) {
  $query = \Drupal::entityQuery('node');
  $nodes = Node::loadMultiple($query->execute());

  foreach ($nodes as $nid => $node) {
    if ($action == 'publish' && $node->title->value == 'API TEST nid_list_alter do not publish me') {
      // Remove the node id.
      $nids = array_diff($nids, [$nid]);
    }
    if ($action == 'publish' && $node->title->value == 'API TEST nid_list_alter publish me') {
      // Set a publish_on date and add the node id.
      $node->set('publish_on', REQUEST_TIME)->save();
      $nids[] = $nid;
    }
    if ($action == 'unpublish' && $node->title->value == 'API TEST nid_list_alter do not unpublish me') {
      // Remove the node id.
      $nids = array_diff($nids, [$nid]);
    }
    if ($action == 'unpublish' && $node->title->value == 'API TEST nid_list_alter unpublish me') {
      // Set an unpublish_on date and add the node id.
      $node->set('unpublish_on', REQUEST_TIME)->save();
      $nids[] = $nid;
    }
  }
  return $nids;
}

/**
 * Implements hook_scheduler_allow_publishing().
 */
function scheduler_api_test_scheduler_allow_publishing($node) {
  // If there is no 'Approved for Publishing' field then allow publishing.
  if (!isset($node->field_approved_publishing)) {
    $allowed = TRUE;
  }
  else {
    // Only publish nodes that have 'Approved for Publishing' set.
    $allowed = $node->field_approved_publishing->value;
    // If publication is denied then inform the user why.
    if (!$allowed) {
      drupal_set_message(t('%title is scheduled for publishing, but will not be published until approved.', ['%title' => $node->title->value]), 'status', FALSE);
      // If the time is in the past it means that the action has been prevented.
      // Write a dblog message to show this. Give a link to view the node but
      // cater for no nid as the node may be new and not yet saved.
      if ($node->publish_on->value <= REQUEST_TIME) {
        \Drupal::logger('scheduler_api_test')->warning('Publishing of "%title" is prevented until approved.', [
          '%title' => $node->title->value,
          'link' => $node->id() ? $node->link(t('View node')) : '',
        ]);
      }
    }
  }
  return $allowed;
}

/**
 * Implements hook_scheduler_allow_unpublishing().
 */
function scheduler_api_test_scheduler_allow_unpublishing($node) {
  // If there is no 'Approved for Unpublishing' field then allow unpublishing.
  if (!isset($node->field_approved_unpublishing)) {
    $allowed = TRUE;
  }
  else {
    // Only unpublish nodes that have 'Approved for Unpublishing' set.
    $allowed = $node->field_approved_unpublishing->value;
    // If unpublication is denied then inform the user why.
    if (!$allowed) {
      drupal_set_message(t('%title is scheduled for unpublishing, but will not be unpublished until approved.', ['%title' => $node->title->value]), 'status', FALSE);
      // If the time is in the past it means that the action has been prevented.
      // Write a dblog message to show this. Give a link to view the node but
      // cater for no nid as the node may be new and not yet saved.
      if ($node->unpublish_on->value <= REQUEST_TIME) {
        \Drupal::logger('scheduler_api_test')->warning('Unpublishing of "%title" is prevented until approved.', [
          '%title' => $node->title->value,
          'link' => $node->id() ? $node->link(t('View node')) : '',
        ]);
      }
    }
  }
  return $allowed;
}
