<?php

/**
 * @file
 * Contains ymca_mindbody.module.
 */

use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\node\NodeInterface;
use Drupal\Core\Datetime\DrupalDateTime;

/**
 * Implements hook_theme().
 */
function ymca_mindbody_theme($existing, $type, $theme, $path) {
  return [
    'mindbody_results_content' => [
      'variables' => [
        'location' => '',
        'program' => '',
        'session_type' => '',
        'trainer' => '',
        'datetime' => '',
        'back_link' => '',
        'start_again_link' => '',
        'base_path' => '',
        'telephone' => '',
        'days' => [],
      ],
      'template' => 'mindbody-results-content',
    ],
    'mindbody_products_list' => [
      'variables' => [
        'products_to_display_member' => [],
        'products_to_display_non_member' => [],
        'modal_content' => '',
      ],
      'template' => 'mindbody-products-list',
    ],
    'mindbody_products_list_location' => [
      'variables' => [
        'products_to_display_member' => [],
        'products_to_display_non_member' => [],
      ],
      'template' => 'mindbody-products-list-location',
    ],
    'mindbody_products_list_modal' => [
      'variables' => [
        'products_to_display_member' => [],
        'products_to_display_non_member' => [],
      ],
      'template' => 'mindbody-products-list-modal',
    ],
    'mindbody_locations_pt_list' => [
      'variables' => [
        'left_col' => '',
        'right_col' => '',
      ],
      'template' => 'mindbody-locations-pt-list',
    ],
  ];
}

/**
 * Implements hook_token_info().
 */
function ymca_mindbody_token_info() {
  $info['tokens']['node']['schedule-pt-location-url'] = [
    'name' => t('Schedule Personal Training'),
    'description' => t('The URL to MindBody form with pre-populated location'),
    'type' => 'url',
  ];
  $info['tokens']['node']['schedule-pt-trainer-url'] = [
    'name' => t('Schedule Appointment with'),
    'description' => t('The URL to MindBody form with pre-populated trainer'),
    'type' => 'url',
  ];
  $info['tokens']['node']['list-of-products-pt'] = [
    'name' => t('List of Personify products'),
    'description' => t('Provides an expander block with list of personify products'),
    'type' => 'markup',
  ];
  $info['tokens']['node']['list-of-products-pt-location'] = [
    'name' => t('List of Personify products for location'),
    'description' => t('Provides an expander block with list of personify products'),
    'type' => 'markup',
  ];
  $info['tokens']['site']['list-of-locations-pt'] = [
    'name' => t('Location PT Links'),
    'description' => t('Provides a list of links to location PT pages.'),
    'type' => 'markup',
  ];

  return $info;
}

/**
 * Implements hook_tokens().
 */
function ymca_mindbody_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = array();

  if ($type == 'site') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'list-of-locations-pt':
          /** @var \Drupal\ymca_mappings\LocationMappingRepository $locationRepo */
          $locationRepo = \Drupal::service('ymca_mappings.location_repository');
          $locationMappings = $locationRepo->loadAll();
          $items = [];

          $aliasManager = \Drupal::service('path.alias_manager');
          $pathValidator = \Drupal::service('path.validator');

          foreach ($locationMappings as $mapping) {
            foreach ($mapping->get('field_location_ref')->referencedEntities() as $location) {
              if ($location->bundle() != 'location') {
                continue;
              }

              $path = $aliasManager->getAliasByPath('/node/' . $location->id());
              $schedulePath = $path . '/health__fitness/personal_training';
              if ($pathValidator->isValid($schedulePath)) {
                $items[] = new Link($location->label(), Url::fromUserInput($schedulePath));
              }
            }
          }

          if (empty($items)) {
            return NULL;
          }

          // Let's create 2 columns.
          $chunks = array_chunk($items, (floor(count($items) / 2)) + 1);

          $variables = [
            '#theme' => 'mindbody_locations_pt_list',
            '#left_col' => [
              '#theme' => 'item_list',
              '#items' => count($chunks[0]) ? $chunks[0] : [],
            ],
            '#right_col' => [
              '#theme' => 'item_list',
              '#items' => count($chunks[1]) ? $chunks[1] : [],
            ],
          ];

          $replacements[$original] = render($variables);

          break;
      }
    }
  }

  if ($type == 'node') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'schedule-pt-location-url':
          if (isset($data['node']) && $data['node'] instanceof NodeInterface) {
            /* @var $site_section \Drupal\node\NodeInterface */
            if ($site_section = \Drupal::service('pagecontext.service')->getContext()) {

              $location_repo = \Drupal::service('ymca_mappings.location_repository');
              if ($mapping = $location_repo->findByLocationId($site_section->id())) {
                $field_mindbody_id = $mapping->field_mindbody_id->getValue();
                $location = isset($field_mindbody_id[0]['value']) ? $field_mindbody_id[0]['value'] : FALSE;
                $url_options = [
                  'query' => [
                    'location' => $location,
                    'context' => 'location',
                  ],
                ];
                $link = new Link(t('Schedule Personal Training'), Url::fromRoute('ymca_mindbody.location.pt', ['node' => $site_section->id()], $url_options));
                $replacements[$original] = $link->toString();
              }

            }
          }
          break;

        case 'schedule-pt-trainer-url':
          if (isset($data['node']) && $data['node'] instanceof NodeInterface) {
            /* @var $node \Drupal\node\NodeInterface */
            $node = $data['node'];
            /* @var $site_section \Drupal\node\NodeInterface */
            if ($site_section = \Drupal::service('pagecontext.service')->getContext()) {

              $location_repo = \Drupal::service('ymca_mappings.location_repository');
              if ($mapping = $location_repo->findByLocationId($site_section->id())) {

                $field_mindbody_id = $mapping->field_mindbody_id->getValue();
                $location = isset($field_mindbody_id[0]['value']) ? $field_mindbody_id[0]['value'] : FALSE;
                $field_location_id = $mapping->field_location_ref->getValue();
                $location_id = isset($field_location_id[0]['target_id']) ? $field_location_id[0]['target_id'] : FALSE;
                $node_title = explode(' ', $node->getTitle());

                $trainer_repo = \Drupal::service('ymca_mappings.trainer_repository');
                if ($mapping = $trainer_repo->findByPageId($node->id())) {
                  $field_mindbody_trainer_id = $mapping->field_mindbody_trainer_id->getValue();
                  $trainer = isset($field_mindbody_trainer_id[0]['value']) ? $field_mindbody_trainer_id[0]['value'] : FALSE;
                  $url_options = [
                    'query' => [
                      'location' => $location,
                      'trainer' => $trainer,
                      'context' => 'trainer',
                    ],
                  ];
                  $link = new Link(t('Schedule Appointment with @title', ['@title' => $node_title[0]]), Url::fromRoute('ymca_mindbody.location.pt', ['node' => $location_id], $url_options));
                  $replacements[$original] = $link->toString();
                }

              }
            }
          }
          break;

        case 'list-of-products-pt':
          // Get mapping repository to access all mappings.
          $mapping_repository = \Drupal::service('ymca_mappings.personify_product_repository');
          $mappings = $mapping_repository->loadAll();

          $products_to_display_member = $products_to_display_non_member = [];

          foreach ($mappings as $mapping) {
            $product_code_array = ymca_mindbody_product_code_parse($mapping->field_product_code->getValue()[0]['value']);

            // Proceed only for mapping without location (for general prices).
            if (empty($mapping->field_location_ref->getValue())) {

              $show_special_prices = FALSE;
              $product_member_price = $mapping->field_member_price->getValue()[0]['value'];
              $product_non_member_price = $mapping->field_nonmember_price->getValue()[0]['value'];
              $product_member_special_price = $mapping->field_special_member_price->getValue()[0]['value'];
              $product_non_member_special_price = $mapping->field_special_non_member_price->getValue()[0]['value'];
              $start_date = $mapping->field_price_available_from->getValue()[0]['value'];
              $end_date = $mapping->field_price_available_to->getValue()[0]['value'];

              // Check special prices should be applied.
              if ($start_date && $end_date) {
                $start_date = new DrupalDateTime($start_date . ' 00:00:00', drupal_get_user_timezone());
                $start_date = $start_date->format('Y-m-d');
                $end_date = new DrupalDateTime($end_date . ' 00:00:00', drupal_get_user_timezone());
                $end_date = $end_date->format('Y-m-d');
                $now = new DrupalDateTime('now', drupal_get_user_timezone());
                $now = $now->format('Y-m-d');
                if ($now >= $start_date && $now <= $end_date) {
                  $show_special_prices = TRUE;
                  // Temporary remove 8 and 12 packages.
                  if ($product_code_array[2] == 8 || $product_code_array[2] == 12) {
                    continue;
                  }
                }
              }
              // Fill in products for members.
              $products_to_display_member[$product_code_array[4]][] = [
                'price' => $product_member_price,
                'special_price' => $product_member_special_price,
                'session' => $product_code_array[4],
                'package' => $product_code_array[2],
                'show_special_prices' => $show_special_prices,
              ];

              // Fill in products for non-members, do not show empty price.
              if (!empty($product_non_member_price)) {
                $products_to_display_non_member[$product_code_array[4]][] = [
                  'price' => $product_non_member_price,
                  'special_price' => $product_non_member_special_price,
                  'session' => $product_code_array[4],
                  'package' => $product_code_array[2],
                  'show_special_prices' => $show_special_prices,
                ];
              }
            }
            // If location is not entered changed data for Drupal settings.
            else {
              $settings['products_codes'][$mapping->field_product_code->getValue()[0]['value']] = [$mapping->field_productid->getValue()[0]['value']];
              $product_location_ids[$product_code_array[0]] = $product_code_array[0];
            }
          }

          krsort($products_to_display_member);
          krsort($products_to_display_non_member);
          if (isset($products_to_display_member[30])) {
            asort($products_to_display_member[30]);
          }
          if (isset($products_to_display_member[60])) {
            asort($products_to_display_member[60]);
          }
          if (isset($products_to_display_non_member[30])) {
            asort($products_to_display_non_member[30]);
          }
          if (isset($products_to_display_non_member[60])) {
            asort($products_to_display_non_member[60]);
          }

          // Get access to location mappings.
          $mapping_repository_location = \Drupal::service('ymca_mappings.location_repository');
          $mappings_location = $mapping_repository_location->findByLocationPersonifyBranchCode($product_location_ids);

          $modal_content = [];
          // Fill a list of locations for modal popup.
          foreach ($mappings_location as $mapping) {
            $modal_content[] = [
              'name' => $mapping->getName(),
              'id' => $mapping->field_location_personify_brcode->getValue()[0]['value'],
            ];
          }

          $config = Drupal::config('ymca_mindbody.settings');
          $settings['personify_product_url'] = $config->get('personify_product_url');
          $variables = [
            '#theme' => 'mindbody_products_list',
            '#attached' => [
              'library' => [
                'ymca_mindbody/ymca_mindbody',
              ],
              'drupalSettings' => $settings,
            ],
            '#products_to_display_member' => $products_to_display_member,
            '#products_to_display_non_member' => $products_to_display_non_member,
            '#modal_content' => $modal_content,
          ];

          $replacements[$original] = render($variables);
          break;

        case 'list-of-products-pt-location':
          if ($site_section = \Drupal::service('pagecontext.service')->getContext()) {
            $location_repo = \Drupal::service('ymca_mappings.location_repository');
            $mapping = $location_repo->findByLocationId($site_section->id());

            // Proceed only if this is location page.
            if ($mapping) {
              $field_location_personify_brcode = $mapping->field_location_personify_brcode->getValue();
              $location = isset($field_location_personify_brcode[0]['value']) ? $field_location_personify_brcode[0]['value'] : FALSE;
              $mapping_repository = \Drupal::service('ymca_mappings.personify_product_repository');
              $mappings = $mapping_repository->loadAll();
              $products_to_display_member = $products_to_display_non_member = [];
              $config = \Drupal::config('ymca_mindbody.settings');
              $personify_product_url = $config->get('personify_product_url');

              // Filter only detected locations (by product code).
              foreach ($mappings as $mapping) {
                $product_code_array = ymca_mindbody_product_code_parse($mapping->field_product_code->getValue()[0]['value']);
                // Proceed only with detected location.
                if ($product_code_array[0] == $location) {
                  $product_member_price = $mapping->field_member_price->getValue()[0]['value'];
                  $product_non_member_price = $mapping->field_nonmember_price->getValue()[0]['value'];
                  $product_member_special_price = $mapping->field_special_member_price->getValue()[0]['value'];
                  $product_non_member_special_price = $mapping->field_special_non_member_price->getValue()[0]['value'];
                  $start_date = $mapping->field_price_available_from->getValue()[0]['value'];
                  $end_date = $mapping->field_price_available_to->getValue()[0]['value'];

                  $show_special_prices = FALSE;
                  if ($start_date && $end_date) {
                    $timezone = drupal_get_user_timezone();
                    $start_date = new DrupalDateTime($start_date . ' 00:00:00', $timezone);
                    $start_date = $start_date->format('Y-m-d');
                    $end_date = new DrupalDateTime($end_date . ' 00:00:00', $timezone);
                    $end_date = $end_date->format('Y-m-d');
                    $now = new DrupalDateTime('now', $timezone);
                    $now = $now->format('Y-m-d');
                    if ($now >= $start_date && $now <= $end_date) {
                      $show_special_prices = TRUE;
                      // Temporary remove 8 and 12 packages.
                      if ($product_code_array[2] == 8 || $product_code_array[2] == 12) {
                        continue;
                      }
                    }
                  }
                  $products_to_display_member[$product_code_array[4]][$product_code_array[2]] = [
                    'price' => $product_member_price,
                    'special_price' => $product_member_special_price,
                    'session' => $product_code_array[4],
                    'package' => $product_code_array[2],
                    'url' => $personify_product_url . $mapping->field_productid->getValue()[0]['value'],
                    'show_special_prices' => $show_special_prices,
                  ];
                  // Fill in products for non-members, do not show empty price.
                  if (!empty($product_non_member_price)) {
                    $products_to_display_non_member[$product_code_array[4]][$product_code_array[2]] = [
                      'price' => $product_non_member_price,
                      'special_price' => $product_non_member_special_price,
                      'session' => $product_code_array[4],
                      'package' => $product_code_array[2],
                      'url' => $personify_product_url . $mapping->field_productid->getValue()[0]['value'],
                      'show_special_prices' => $show_special_prices,
                    ];
                  }

                }
              }

              krsort($products_to_display_member);
              krsort($products_to_display_non_member);
              if (isset($products_to_display_member[30])) {
                asort($products_to_display_member[30]);
              }
              if (isset($products_to_display_member[60])) {
                asort($products_to_display_member[60]);
              }
              if (isset($products_to_display_non_member[30])) {
                asort($products_to_display_non_member[30]);
              }
              if (isset($products_to_display_non_member[60])) {
                asort($products_to_display_non_member[60]);
              }

              $variables = [
                '#theme' => 'mindbody_products_list_location',
                '#products_to_display_member' => $products_to_display_member,
                '#products_to_display_non_member' => $products_to_display_non_member,
              ];

              $replacements[$original] = render($variables);
            }
          }
          break;
      }
    }
  }
  return $replacements;
}

/**
 * Implements hook_mindbody_cache_proxy_update_stats().
 */
function ymca_mindbody_mindbody_cache_proxy_update_stats($data) {
  $config = Drupal::config('mindbody_cache_proxy.settings');
  if ($data->miss == $config->get('calls')) {
    \Drupal::service('cache_tags.invalidator')->invalidateTags(['mindbody_state']);
  }
}

/**
 * Implements hook_mindbody_cache_proxy_flush_stats().
 */
function ymca_mindbody_mindbody_cache_proxy_flush_stats($data) {
  \Drupal::service('cache_tags.invalidator')->invalidateTags(['mindbody_state']);
}

/**
 * Implements hook_mail().
 */
function ymca_mindbody_mail($key, &$message, $params) {
  switch ($key) {
    case 'notify_trainer':

      $body = [
        "<p>$params[trainer_name],</p>",
        "$params[client_name] has scheduled an appointment with you at $params[start_date].</p>",
        "<p>If you need to change this appointment, please contact:</p>",
        "<ul>",
        "<li>Name: $params[client_name]</li>",
        "<li>Email: $params[client_email]</li>",
        "<li>Phone: $params[client_phone]</li>",
        "</ul>",
        "<p>Thank you!<br />",
        "The $params[location] Team</p>",
      ];

      $message['subject'] = "Online Booking Confirmation for $params[start_date]";
      $message['body'][] = implode('', $body);

      break;

    case 'notify_customer':
      $body = [
        "<p>$params[client_name],</p>",
        "<p>You have scheduled an appointment with $params[trainer_name] at $params[start_date].</p>",
        "<p>If you need to change this appointment, please contact:</p>",
        "<ul>",
        "<li>Name: $params[trainer_name]</li>",
        "<li>Email: $params[trainer_email]</li>",
        "<li>Phone: $params[trainer_phone]</li>",
        "</ul>",
        "<p>Thank you!<br />",
        "The $params[location] Team</p>",
      ];

      $message['subject'] = "Online Booking Confirmation for $params[start_date].";
      $message['body'][] = implode('', $body);

      break;

    case 'notify_location_trainers':
      $body = [
        "<p>$params[trainer_name],</p>",
        "<p>$params[client_name] has purchased $params[item_name]. Please follow up with $params[client_name] to schedule sessions.</p>",
        "<p>Order/Customer information:</p>",
        "<ul>",
        "<li>MindBody SaleID: $params[mb_sale_id]</li>",
        "<li>Personify OrderNo: $params[personify_order_no]</li>",
        "<li>Personify OrderLineNo: $params[personify_order_line_no]</li>",
        "<li>Price: $params[total_amount]</li>",
        "<li>Name: $params[client_name]</li>",
        "<li>Email: $params[client_email]</li>",
        "<li>Phone: $params[client_phone]</li>",
        "</ul>",
        "<p>Thank you!<br />",
        "The $params[location] Team</p>",
      ];

      $message['subject'] = "$params[client_name] has purchased $params[item_name].";
      $message['body'][] = implode('', $body);
      break;

    case 'notify_location_trainer_saleid':
      $body = [
        "<p>$params[trainer_name],</p>",
        "<p>$params[client_name] has purchased $params[item_name], but we cannot automatically assign SaleID for that order.</p>",
        "<p>Please contact site admin to resolve that issue.</p>",
        "<p>Customer information:</p>",
        "<ul>",
        "<li>Personify OrderNo: $params[personify_order_no]</li>",
        "<li>Personify OrderLineNo: $params[personify_order_line_no]</li>",
        "<li>Name: $params[client_name]</li>",
        "<li>Email: $params[client_email]</li>",
        "<li>Phone: $params[client_phone]</li>",
        "</ul>",
        "<p>Thank you!<br />",
        "The $params[location] Team</p>",
      ];

      $message['subject'] = "Cannot assign SaleID for purchase by $params[client_name], $params[item_name].";
      $message['body'][] = implode('', $body);
      break;

    case 'notify_order_cancel':
      $body = [
        "<p>$params[trainer_name],</p>",
        "<p>$params[client_name] has received a refund for $params[item_name]. Please remember to go into MINDBODY and delete this item from $params[client_name]'s account details.</p>",
        "<ul>",
        "<li>Personify Order #: $params[personify_order_no]</li>",
        "<li>Personify Order Line #: $params[personify_order_line_no]</li>",
        "<li>MINDBODY Sale ID: $params[mb_sale_id]</li>",
        "<li>Client email: $params[client_email]</li>",
        "<li>Client phone: $params[client_phone]</li>",
        "</ul>",
        "<p>Please follow up with <CLIENTNAME> if you believe this is inaccurate.</p>",
        "<p>Thank you!<br />",
        "The $params[location] Team<br />",
        "Web: <a href=\"http://ymcamn.org\">http://ymcamn.org</a></p>",
      ];

      $message['subject'] = "MINDBODY refund for $params[client_name] for $params[item_name].";
      $message['body'][] = implode('', $body);
      break;

    case 'notify_of_failed_orders':
      $body = [
        $params['data'],
      ];

      $message['subject'] = t('New failed orders since @date', ['@date' => $params['last_run_date']]);
      $message['body'][] = implode('', $body);

      break;
  }
}

/**
 * Parse product code in right array.
 */
function ymca_mindbody_product_code_parse($product_code) {
  // Location.
  $product_code_array = explode('_', $product_code);
  $location = $product_code_array[0];

  if (strpos($product_code, 'PT_MP_INTRO') !== FALSE) {
    $product_code_array = [0 => $location, 2 => '3', 4 => '60'];
  }
  elseif (strpos($product_code, 'MEM_PROMO') !== FALSE) {
    $product_code_array = [0 => $location, 2 => '2', 4 => '30'];
  }
  return $product_code_array;
}
