<?php

/**
 * @file
 * Contains ymca_mappings.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ymca_mappings_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ymca_mappings module.
    case 'help.page.ymca_mappings':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ymca_mappings_theme() {
  $theme = [];
  $theme['mapping'] = [
    'render element' => 'elements',
    'file' => 'ymca_mappings.page.inc',
    'template' => 'mapping',
  ];
  $theme['mapping_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'ymca_mappings.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function ymca_mappings_theme_suggestions_mapping(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#mapping'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'mapping__' . $sanitized_view_mode;
  $suggestions[] = 'mapping__' . $entity->bundle();
  $suggestions[] = 'mapping__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'mapping__' . $entity->id();
  $suggestions[] = 'mapping__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
