<?php

/**
 * @file
 * OpenY Node Activity module file.
 */

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * This will publish/unpublish Activity nodes when a Category is updated.
 */
function openy_node_activity_node_update(Drupal\Core\Entity\EntityInterface $entity) {
  // Only do this for Category nodes.
  if ($entity->getType() != 'program_subcategory') {
    return;
  }

  // Published will be true, unpublished false.
  $original_status = $entity->original->isPublished();
  $current_status = $entity->isPublished();

  // Going from published to unpublished.
  if ($original_status && !$current_status) {
    $activities = _openy_node_activity_getactivitynodes($entity);

    // Unpublish all Activity nodes.
    foreach ($activities as $node) {
      if ($node->isPublished()) {
        $node->setUnPublished();
        $node->save();
      }
    }
  } elseif (!$original_status && $current_status) {
    // Going from unpublished to published. We have to just publish everything.
    $activities = _openy_node_activity_getactivitynodes($entity);

    // Publish all Activity nodes.
    foreach ($activities as $node) {
      if (!$node->isPublished()) {
        $node->setPublished();
        $node->save();
      }
    }
  }

}

/**
 * Helper function to retrieve the list of Activity nodes that references this
 * Category node.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The Category node who's Activity nodes will be retrieved.
 *
 * @return array $activities
 *   Array of Activity nodes.
 */
function _openy_node_activity_getactivitynodes(&$entity) {
  $category_id = $entity->id();

  $connection = \Drupal::database();

  $query = $connection->select('node__field_activity_category', 'c');
  $query->condition('c.field_activity_category_target_id', $category_id);
  $query->addField('c', 'entity_id');
  $result = $query->execute()->fetchAllAssoc('entity_id');

  $activity_ids = array_keys($result);
  $activities = \Drupal::entityTypeManager()->getStorage('node')->loadMultiple($activity_ids);

  return $activities;
}
