<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function openy_focal_point_theme($existing, $type, $theme, $path) {
  return [
    'openy_focal_point_preview' => [
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter() for media_image_edit_form.
 */
function openy_focal_point_form_media_image_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $paragraph_type = \Drupal::request()->query->get('paragraph_type');
  $field_name = \Drupal::request()->query->get('field_name');

  if (!$paragraph_type || !$field_name) {
    return;
  }

  $form['actions']['submit']['#ajax']['options']['query'] += [
    'paragraph_type' => $paragraph_type,
    'field_name' => $field_name,
  ];
}
