<?php

/**
 * @file
 * Open Y Paragraph News Listing install file.
 */

/**
 * Update feature configs.
 */
function openy_prgf_news_listing_update_8001() {
  $config_dir = drupal_get_path('module', 'openy_prgf_news_listing') . '/config/install/';
  $config_importer = \Drupal::service('openy_upgrade_tool.importer');
  $config_importer->setDirectory($config_dir);
  $config_importer->importConfigs([
    'views.view.listing_news_posts',
  ]);
}
