<?php

/**
 * @file
 * Hooks and routines for the openy_update module.
 */

/**
 * Implements hook_update_status_alter().
 */
function openy_update_update_status_alter(&$projects) {
  $client = \Drupal::httpClient();
  $response = $client->post('http://openy.org:1880/packages', [
    'body' => json_encode($projects),
  ]);
  $body = $response->getBody();
  $body = $body->getContents();
  $projects = json_decode($body, TRUE);
}
