<?php

/**
 * @file
 * Installation file.
 */

/**
 * Add field_camp_menu field to Camp and Landing CT.
 */
function openy_location_core_update_8001() {
  $features = [
    'openy_node_camp',
    'openy_node_landing',
  ];
  /* @var \Drupal\config_import\Confi$featuresgFeaturesImporterServiceInterface $features_importer */
  $features_importer = \Drupal::service('config_import.features_importer');
  $features_importer->importFeatures($features);
}
