<?php

/**
 * @file
 * OpenY digital signage blocks module.
 */

/**
 * Implements hook_theme().
 */
function openy_digital_signage_blocks_theme($existing, $type, $theme, $path) {
  return [
    'openy_digital_signage_blocks_static_ticker' => [
      'template' => 'openy-digital-signage-blocks-static-ticker',
      'variables' => [
        'icon' => 'bell',
        'message' => '',
        'wrapper_attributes' => NULL,
      ],
    ],
    'openy_digital_signage_blocks_system_message' => [
      'template' => 'openy-digital-signage-blocks-system-message',
      'variables' => [
        'icon' => 'bell',
        'message' => '',
        'wrapper_attributes' => NULL,
      ],
    ],
  ];
}
