<?php

/**
 * @file
 * OpenY digital signage blocks module.
 */

define('OPENY_DS_BLOCK_PROMOTIONAL', 'digital_signage_promotional');

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function openy_digital_signage_blocks_theme($existing, $type, $theme, $path) {
  return [
    'openy_digital_signage_blocks_static_ticker' => [
      'template' => 'openy-digital-signage-blocks-static-ticker',
      'variables' => [
        'icon' => 'bell',
        'message' => '',
        'wrapper_attributes' => NULL,
      ],
    ],
    'openy_digital_signage_blocks_system_message' => [
      'template' => 'openy-digital-signage-blocks-system-message',
      'variables' => [
        'icon' => 'bell',
        'message' => '',
        'wrapper_attributes' => NULL,
      ],
    ],
    'block__digital_signage_promotional' => [
      'template' => 'block--digital-signage-promotional',
      'render element' => 'elements',
      'base hook' => 'block',
    ],
    'openy_digital_signage_block_time' => [
      'template' => 'openy-digital-signage-block-time',
      'variables' => [
        'wrapper_attributes' => NULL,
        'current_time' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_block().
 */
function openy_digital_signage_blocks_theme_suggestions_block(array $variables) {
  if ($variables['elements']['#base_plugin_id'] != 'block_content') {
    return;
  }
  /* @var \Drupal\block_content\Entity\BlockContent $block */
  $block = $variables['elements']['content']['#block_content'];
  $digital_singage_bundles = [
    OPENY_DS_BLOCK_PROMOTIONAL,
  ];
  if (!in_array($block->bundle(), $digital_singage_bundles)) {
    return;
  }
  // Add suggestion.
  $suggestions = [];
  $suggestions[] = 'block__' . $block->bundle();
  return $suggestions;
}

/**
 * Implements hook_preprocess_block() for block templates.
 */
function openy_digital_signage_blocks_preprocess_block(&$variables) {
  if ($variables['base_plugin_id'] != 'block_content') {
    return;
  }
  /* @var \Drupal\block_content\Entity\BlockContent $block */
  $block = $variables['content']['#block_content'];
  $digital_singage_bundles = [
    OPENY_DS_BLOCK_PROMOTIONAL,
  ];
  if (!in_array($block->bundle(), $digital_singage_bundles)) {
    return;
  }

  $variables['attributes']['class'][] = 'openy-digital-signage-block-promotional';

  $attributes = new Attribute();
  $attributes->addClass('block-promotional');
  $attributes->addClass('block-promotional-background-' . $block->field_ds_background_size->value);
  $attributes->addClass('block-promotional-background-' . $block->field_ds_background_position->value);
  $attributes->addClass('block-promotional-background-' . $block->field_ds_background_scheme->value);
  $attributes->addClass('block-promotional-color-' . $block->field_ds_color_scheme->value);
  $attributes->addClass('block-promotional-message-position-' . $block->field_ds_message_position->value);
  $background_styles = ['background-color: ' . $block->field_ds_background_color->value . ';'];
  if ($background_image = $block->field_ds_background_image->entity) {
    $background_styles[] = 'background-image:url(' . file_create_url($background_image->getFileUri()) . ');';
  }
  $attributes->setAttribute('style', $background_styles);
  $variables['wrapper_attributes'] = $attributes;
}

/**
 * Implements hook_form_alter().
 */
function openy_digital_signage_blocks_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id != 'block_content_digital_signage_promotional_panels_ipe_form') {
    return;
  }
  $form['revision_information']['#access'] = FALSE;

  $form['background_image_settings'] = [
    '#type' => 'fieldset',
    '#title' => t('Background Image settings'),
    '#collapsible' => TRUE,
    '#weight' => $form['field_ds_background_image']['#weight'],
  ];
  $form['background_image_settings']['field_ds_background_image'] = $form['field_ds_background_image'];
  unset($form['field_ds_background_image']);
  $form['background_image_settings']['field_ds_background_position'] = $form['field_ds_background_position'];
  unset($form['field_ds_background_position']);
  $form['background_image_settings']['field_ds_background_size'] = $form['field_ds_background_size'];
  unset($form['field_ds_background_size']);
}
