<?php

/**
 * @file
 * Provides a UI for Page Manager.
 */

use Drupal\page_manager_ui\Entity\PageListBuilder;
use Drupal\page_manager_ui\Form\PageAddForm;
use Drupal\page_manager_ui\Form\PageDeleteForm;
use Drupal\page_manager_ui\Form\PageEditForm;
use Drupal\page_manager_ui\Form\PageVariantAddForm;
use Drupal\page_manager_ui\Form\PageVariantDeleteForm;
use Drupal\page_manager_ui\Form\PageVariantEditForm;

/**
 * Implements hook_entity_type_build().
 */
function page_manager_ui_entity_type_build(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  $entity_types['page']
    ->setListBuilderClass(PageListBuilder::class)
    ->setFormClass('add', PageAddForm::class)
    ->setFormClass('edit', PageEditForm::class)
    ->setFormClass('delete', PageDeleteForm::class)
    ->setLinkTemplate('collection', '/admin/structure/page_manager')
    ->setLinkTemplate('add-form', '/admin/structure/page_manager/add')
    ->setLinkTemplate('edit-form', '/admin/structure/page_manager/manage/{page}')
    ->setLinkTemplate('delete-form', '/admin/structure/page_manager/manage/{page}/delete')
    ->setLinkTemplate('enable', '/admin/structure/page_manager/manage/{page}/enable')
    ->setLinkTemplate('disable', '/admin/structure/page_manager/manage/{page}/disable');

  $entity_types['page_variant']
    ->setFormClass('add', PageVariantAddForm::class)
    ->setFormClass('edit', PageVariantEditForm::class)
    ->setFormClass('delete', PageVariantDeleteForm::class)
    ->setLinkTemplate('edit-form', '/admin/structure/page_manager/manage/{page}/variant/{page_variant}')
    ->setLinkTemplate('delete-form', '/admin/structure/page_manager/manage/{page}/variant/{page_variant}/delete');
}
