<?php

/**
 * @file
 * Contains openy_activity_finder module hooks.
 */

/**
 * Implements hook_theme().
 */
function openy_activity_finder_theme() {
  return [
    'openy_activity_finder_program_search' => [
      'variables' => [
        'data' => [],
        'ages' => [],
        'days' => [],
        'categories' => [],
        'categories_type' => '',
        'activities' => [],
        'locations' => [],
        'is_search_box_disabled' => '',
        'expanderSectionsConfig' => [],
      ],
    ],
    'openy_activity_finder_program_search_page' => [
      'variables' => [
        'locations' => [],
        'categories' => [],
        'categories_type' => '',
        'ages' => [],
        'days' => [],
        'is_search_box_disabled' => '',
        'is_spots_available_disabled' => '',
        'expanderSectionsConfig' => [],
        'sort_options' => [],
      ],
    ],
  ];
}
