<?php

/**
 * @file
 * Hook implementations for openy_digital_signage_screen module.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_ENTITY_TYPE_build_defaults_alter().
 */
function openy_digital_signage_screen_openy_digital_signage_screen_build_defaults_alter(&$build, $entity, $view_mode) {
  // Empty.
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function openy_digital_signage_screen_openy_digital_signage_screen_view(&$build, $entity, $display, $view_mode) {
  // Empty.
}

/**
 * Implements hook_theme().
 */
function openy_digital_signage_screen_theme($existing, $type, $theme, $path) {
  return [
    'page__screen' => [
      'template' => 'pages/page--screen',
    ],
  ];
}

/**
 * Implements hook_theme_HOOK_alter().
 */
function openy_digital_signage_screen_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name == 'entity.openy_digital_signage_screen.canonical') {
    array_push($suggestions, 'page__screen');
  }
}

/**
 * Implements hook_preprocess_html().
 */
function openy_digital_signage_screen_preprocess_html(&$variables) {
  $classes = ['page-schedule scheme-orange'];
  $route_name = \Drupal::service('current_route_match')->getRouteName();

  if (empty($variables['attributes'])) {
    $variables['attributes'] = new Attribute();
  }

  if ($route_name == 'entity.openy_digital_signage_screen.canonical') {
    $variables['attributes']->addClass($classes);
  }
}

/**
 * Implements hook_preprocess_page().
 */
function openy_digital_signage_screen_preprocess_page(&$variables) {
  $variables['base_path'] = base_path();
}
