<?php

/**
 * @file
 * Hook implementations for openy_digital_signage_screen module.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_ENTITY_TYPE_build_defaults_alter().
 */
function openy_digital_signage_screen_openy_digital_signage_screen_build_defaults_alter(&$build, $entity, $view_mode) {
  // Empty.
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function openy_digital_signage_screen_openy_digital_signage_screen_view(&$build, $entity, $display, $view_mode) {
  // Empty.
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function openy_digital_signage_screen_node_view_alter(&$build, $entity, $display, $view_mode = '') {
  if ($entity->bundle() == 'screen_content') {
    $build['#attached']['library'][] = 'openy_digital_signage_screen/openy_ds_screen_theme';
  }
}

/**
 * Implements hook_preprocess().
 */
function openy_digital_signage_screen_preprocess_block(&$variables) {
  $block_plugin_manager = \Drupal::service('plugin.manager.block');
  $definition = $block_plugin_manager->getDefinition($variables['plugin_id']);
  if (!isset($variables['attributes']['class'])) {
    $variables['attributes']['class'] = array();
  }
  $variables['attributes']['class'][] = 'block-wrapper';
  $variables['attributes']['class'][] = 'block-provider--' . $definition['provider'];
  $variables['attributes']['class'][] = 'block-plugin-id--' . $variables['plugin_id'];
  if ($definition['provider'] == 'block_content') {
    $variables['attributes']['class'][] = 'block-block-content-bundle--' . $variables['content']['#block_content']->bundle();
  }
}

/**
 * Implements hook_theme().
 */
function openy_digital_signage_screen_theme($existing, $type, $theme, $path) {
  return [
    'page__screen' => [
      'template' => 'pages/page--screen',
    ],
  ];
}

/**
 * Implements hook_theme_HOOK_alter().
 */
function openy_digital_signage_screen_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name == 'entity.openy_digital_signage_screen.canonical') {
    array_push($suggestions, 'page__screen');
  }
  elseif ($route_name == 'entity.node.canonical') {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node->bundle() == 'screen_content') {
      array_push($suggestions, 'page__screen');
    }
  }
}

/**
 * Implements hook_preprocess_html().
 */
function openy_digital_signage_screen_preprocess_html(&$variables) {
  $classes = ['page-schedule scheme-orange'];
  $route_name = \Drupal::service('current_route_match')->getRouteName();

  if (empty($variables['attributes'])) {
    $variables['attributes'] = new Attribute();
  }

  if ($route_name == 'entity.openy_digital_signage_screen.canonical') {
    $variables['attributes']->addClass($classes);
  }
}

/**
 * Implements hook_preprocess_page().
 */
function openy_digital_signage_screen_preprocess_page__screen(&$variables) {
  $variables['base_path'] = base_path();
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name == 'entity.node.canonical') {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node->bundle() == 'screen_content') {
      unset($variables['page']['content']['tabs']);
    }
  }
}

/**
 * Implements hook_ds_version().
 */
function openy_digital_signage_screen_ds_version() {
  return '0.0.1';
}
