<?php

/**
 * @file
 * Contains openy_repeat module hooks.
 */

/**
 * Implements hook_theme().
 */
function openy_repeat_theme() {
  return [
    'openy_repeat_schedule_dashboard' => [
      'variables' => [
        'locations' => [],
        'checked_locations' => [],
        'modal' => []
      ],
    ],
    'openy_repeat_schedule_locations' => [
      'variables' => [
        'locations' => [],
      ],
    ],
  ];
}
