<?php

/**
 * @file
 * Contains openy_repeat module hooks.
 */

/**
 * Implements hook_theme().
 */
function openy_repeat_theme() {
  $limit = \Drupal::config('openy_repeat.settings')->get('calendar_limit_days');

  return [
    'openy_repeat_schedule_dashboard' => [
      'variables' => [
        'locations' => [],
        'categories' => [],
        'checked_locations' => [],
        'checked_categories' => [],
        'calendar_limit' => $limit,
        'filters' => [],
      ],
    ],
    'openy_repeat_schedule_locations' => [
      'variables' => [
        'locations' => [],
      ],
    ],
    'openy_repeat__pdf__body' => [
      'variables' => [
        'content' => [],
      ],
    ],
    'openy_repeat__pdf__table__activity' => [
      'variables' => [
        'content' => [],
      ],
    ],
    'openy_repeat__pdf__table__day' => [
      'variables' => [
        'content' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function openy_repeat_page_attachments(array &$attachments) {
  $limit = \Drupal::config('openy_repeat.settings')->get('calendar_limit_days');
  $attachments['#attached']['drupalSettings']['openy_repeat']['calendarLimitDays'] = $limit;
}
