<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_operation().
 */
function tango_card_entity_operation(EntityInterface $entity) {
  $operations = array();

  if ($entity->getEntityTypeId() == 'tango_card_account') {
    $operations['fund'] = array(
      'title' => t('Fund'),
      'weight' => 0,
      'url' => $entity->toUrl('fund-form'),
    );
  }

  return $operations;
}
