<?php

/**
 * @file
 * Main module's file.
 */

/**
 * Implements hook_openy_repeat_results_alter().
 */
function openy_gxp_openy_repeat_results_alter(&$results, $request) {
  $timestamp = $request->get('date');
  if (empty($timestamp)) {
    $timestamp = date('F j, l 00:00:00');
  }
  $timestamp = strtotime($timestamp);
  foreach ($results as &$row) {
    if (strpos($row->register_url, 'groupexpro') !== FALSE) {
      // [2-digit-month]/[2-digit-day]/[4-digit-year].
      $row->register_url .= '/' . date('m', $timestamp) . '/' . date('d', $timestamp) . '/' . date('Y', $timestamp);
    }
  }
}
