<?php

/**
 * @file
 * Open Y Node Class module file.
 */

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * This will publish/unpublish Class nodes when an Activity is updated.
 */
function openy_node_class_node_update(Drupal\Core\Entity\EntityInterface $entity) {
  // Only do this for Activity nodes.
  if ($entity->getType() != 'activity') {
    return;
  }
  // A Draft has been created – ignore.
  if (!$entity->isDefaultRevision()) {
    return;
  }

  // Published will be true, unpublished false.
  $original_status = $entity->original->isPublished();
  $current_status = $entity->isPublished();

  if ($original_status && !$current_status) {
    // Going from published to unpublished.
    $status = false;
  } elseif (!$original_status && $current_status) {
    // Going from unpublished to published.
    $status = true;
  } else {
    // Status was unchanged.
    return;
  }

  $class_ids = _openy_node_class_getclassnodes($entity);
  $batch = [
    'title' => t('Updating @type...', ['@type' => 'classes']),
    'operations' => [
      [
        '\Drupal\openy_node\BatchNodeUpdate::update',
        [
          $class_ids,
          $status,
          'class',
        ],
      ],
    ],
    'finished' => '\Drupal\openy_node\BatchNodeUpdate::finished',
  ];
  batch_set($batch);

}

/**
 * Helper function to retrieve the list of Class node ids that reference this
 * Activity node.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The Activity node who's Class nodes will be retrieved.
 *
 * @return array $class_ids
 *   Array of Class node ids.
 */
function _openy_node_class_getclassnodes(&$entity) {
  $activity_id = $entity->id();

  $connection = \Drupal::database();

  $query = $connection->select('node__field_class_activity', 'c');
  $query->condition('c.field_class_activity_target_id', $activity_id);
  $query->addField('c', 'entity_id');
  $result = $query->execute()->fetchAllAssoc('entity_id');

  $class_ids = array_keys($result);

  return $class_ids;
}
