<?php

/**
 * @file
 * Contains yptf_master specific functions.
 */

use Drupal\ymca_mappings\Entity\Mapping;
use Drupal\views\ViewExecutable;
use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Update/Populate "Personify Product" mappings.
 */
function yptf_master_product_updates_april_2017() {
  // Delete all personify_product mappings.
  $ids = \Drupal::entityQuery('mapping')
    ->condition('type', 'personify_product')
    ->execute();

  $storage = \Drupal::getContainer()
    ->get('entity.manager')
    ->getStorage('mapping');
  $entities = $storage->loadMultiple($ids);
  $storage->delete($entities);

  // Read CSV file with map.
  $path = drupal_get_path('module', 'yptf_master');
  $csv_file = $path . '/misc/PROD_PT_products_for_import_2017.csv';
  $map = array_map('str_getcsv', file($csv_file));

  // Map and create new personify_product.
  foreach ($map as $product) {
    $product_code = $product[4];
    if (strpos($product_code, 'PT_MP_INTRO') !== FALSE) {
      $product_code_array = [2 => '3', 4 => '60'];
    }
    elseif (strpos($product_code, 'MEM_PROMO') !== FALSE) {
      $product_code_array = [2 => '2', 4 => '30'];
    }
    else {
      $product_code_array = explode('_', $product_code);
    }

    $data = [
      'type' => 'personify_product',
      'field_productid' => $product[1],
      'field_member_price' => $product[12],
      'field_nonmember_price' => $product[13],
      'field_package' => $product_code_array[2],
      'field_product_code' => $product[4],
      'field_product_code_nonm' => $product[5],
      'field_session_length' => $product_code_array[4],
    ];
    $mapping_repository = \Drupal::service('ymca_mappings.location_repository');
    $mapping = $mapping_repository->findByLocationPersonifyBranchCode($product[9]);
    $mapping = is_array($mapping) ? reset($mapping) : $mapping;
    if ($mapping && $mapping->hasField('field_location_ref')) {
      $location_id = $mapping->field_location_ref->getValue()[0]['target_id'];
      $data['field_location_ref'] = $location_id;
    }

    $mapping = Mapping::create($data);
    $product[6] = str_replace('MEMBER PROMO Personal Training:', 'MEMBER PROMO PT:', $product[6]);
    $mapping->setName($product[6]);
    $mapping->save();
  }

}
