<?php

/**
 * @file
 * Open Y Taxonomy Blog Category module file.
 */

/**
 * Implements hook_modules_installed().
 */
function openy_txnm_blog_category_modules_installed($modules) {
  if (in_array('simple_sitemap', $modules)) {
    // Import simple_sitemap settings for blog_category on module install.
    $config_importer = \Drupal::service('openy_upgrade_tool.importer');
    $config_dir = drupal_get_path('module', 'openy_txnm_blog_category') . '/config/install';
    $config_importer->setDirectory($config_dir);
    $config_importer->importConfigs(['simple_sitemap.bundle_settings.taxonomy_term.blog_category']);
  }
}
