<?php

/**
 * @file
 * OpenY Entity Reference Tweaks module file.
 */

/**
 * Implements hook_field_widget_form_alter().
 *
 * Alters default entity reference widget in favor of openy_er.
 */
function openy_er_field_widget_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  $settings = $context['items']->getSettings();
  // Entity reference fields contain handler in form 'handler:entity_type'.
  if (!isset($settings['handler']) || !preg_match('/.*:.*/', $settings['handler'])) {
    return;
  }
  list($type, $entity_type) = explode(':', $settings['handler']);
  // We only massage form if the handler is derived from default_no_dep.
  if ($type != 'default_no_dep') {
    return;
  }
  // Reduce the list of options if 'bundle' field is presented.
  if (!isset($element['actions']['bundle'])) {
    return;
  }

  $target_bundles = $settings['handler_settings']['target_bundles_no_dep'];
  $options = &$element['actions']['bundle']['#options'];
  foreach ($options as $key => $option) {
    if (isset($target_bundles[$key])) {
      continue;
    }
    unset($options[$key]);
  }
}
