<?php

/**
 * @file
 * Update routines.
 */

/**
* Add Area taxonomy terms to the sitemap.
*/
function openy_demo_tarea_update_8001() {
  $config_dir = drupal_get_path('module', 'openy_demo_tarea');
  $config_dir .= '/config/install/';
  // Import new configuration.
  $config_importer = \Drupal::service('openy_upgrade_tool.importer');
  $config_importer->setDirectory($config_dir);
  $config_importer->importConfigs([
    'simple_sitemap.bundle_settings.taxonomy_term.area',
  ]);
}
