<?php

/**
 * Implements hook_install().
 */
function openy_hide_node_install(){
  $config = \Drupal::configFactory()->getEditable('views.view.frontpage');
  $config->set('display.page_1.display_options.enabled', FALSE);
  $config->save();
}

/**
 * Implements hook_uninstall().
 */
function openy_hide_node_uninstall() {
  $config = \Drupal::configFactory()->getEditable('views.view.frontpage');
  $config->set('display.page_1.display_options.enabled', TRUE);
  $config->save();
}
