<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_ID_alter().
 */
function openy_hide_node_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state, $form_id){
  $status = \Drupal::config('views.view.frontpage')
    ->get('display.page_1.display_options.enabled');

  $form['front_page']['hide_node'] = [
    '#type' => "checkbox",
    '#title' => t('Disable /node page'),
    '#default_value' => ($status) ? 0 : 1,
  ];

  $form['actions']['submit']['#submit'][] = 'openy_hide_node_form_submit';
}

/**
 * Submit.
 */
function openy_hide_node_form_submit(array $form, FormStateInterface $form_state) {
  $status = ($form_state->getValue('hide_node') == 1) ? FALSE : TRUE;

  $config = \Drupal::configFactory()->getEditable('views.view.frontpage');
  $config->set('display.page_1.display_options.enabled', $status);
  $config->save();
}
