<?php

/**
 * @file
 * Main module's file.
 */

/**
 * Import demo content from Twin Cities account.
 */
function openy_gxp_import_tc() {
  $config = \Drupal::service('config.factory')->getEditable('openy_gxp.settings');
  $config->set('client_id', 3)->save();

  $query = \Drupal::entityQuery('node')
    ->condition('type', 'activity')
    ->condition('title', 'Group Exercise Classes');
  $results = $query->execute();
  $group_exercises_nid = reset($results);

  $config->set('activity', $group_exercises_nid)->save();

  $locations_mapping = '33,West YMCA
  26,East YMCA';
  $config->set('locations', $locations_mapping)->save();

  $config->save();

  foreach (explode("\n", $locations_mapping) as $row) {
    list($gxpLocationId, $locationName) = explode(',', $row);
    $gxpLocationId = (int) $gxpLocationId;
    $locationName = trim($locationName);
    $nids = \Drupal::entityQuery('node')
      ->condition('title', $locationName)
      ->execute();
    if (!empty($nids)) {
      \Drupal\openy_gxp\Form\ImportForm::generateProgramsCSV($config->get('activity'), $config->get('client_id'), $gxpLocationId, reset($nids));
      \Drupal\openy_gxp\Form\ImportForm::migrateOfferings($gxpLocationId);
    }
  }
}

/**
 * Implements hook_openy_repeat_results_alter().
 */
function openy_gxp_openy_repeat_results_alter(&$results, $request) {
  $timestamp = $request->get('date');
  if (empty($timestamp)) {
    $timestamp = date('F j, l 00:00:00');
  }
  $timestamp = strtotime($timestamp);
  foreach ($results as &$row) {
    if (strpos($row->register_url, 'groupexpro') !== FALSE) {
      // [2-digit-month]/[2-digit-day]/[4-digit-year].
      $row->register_url .= '/' . date('m', $timestamp) . '/' . date('d', $timestamp) . '/' . date('Y', $timestamp);
    }
  }
}
