<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_page_bottom().
 */
function redwing_alters_page_bottom(array &$page_bottom) {
  // Insert call tracking link to all pages.
  $page_bottom['redwing_alters'] = [
    '#type' => 'inline_template',
    '#template' => '{{ html | raw }}',
    '#context' => [
      'html' => '<script type="text/javascript" src="//cdn.callrail.com/companies/178817538/999e19f6d2f17cf6389b/12/swap.js"></script>',
    ],
  ];
}
