<?php

/**
 * @file
 * Contains ymca_sync.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ymca_sync_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ymca_sync module.
    case 'help.page.ymca_sync':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('YMCA Sync services. Webservises.') . '</p>';
      return $output;

    default:
  }
}
