<?php
/**
 * @file
 * Helper module for page_manager test.
 */

use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_block_view_alter().
 */
function page_manager_test_block_view_alter(array &$build, BlockPluginInterface $block) {
  $label = $build['#configuration']['label'];
  if ($label == 'Label to be altered') {
    // Change the block label for PageManagerAdminTest::doTestAlterBlock()
    $build['#configuration']['label'] = 'Altered label';
  }
}
