<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme().
 */
function openy_block_expander_theme($existing, $type, $theme, $path) {
  return [
    // Make Drupal aware of our node template for my view mode.
    'page__openy_block_expander_demo' => [
      'base hook' => 'page',
    ],
    'expander_block' => [
      'variables' => [
        'header' => NULL,
        'content' => NULL,
        'entity' => NULL,
      ],
      'template' => 'expander-block',
    ],
  ];
}

/**
 * Implements hook_preprocess().
 */
function openy_block_expander_preprocess(&$variables, $hook, &$info) {
  if ($node = \Drupal::routeMatch()->getRouteName() == 'openy_block_expander.demo') {
    if ($hook == 'page') {
      if (substr($info['theme path'], 0, 7) != 'themes/') {
        $info['theme path'] = drupal_get_path('module', 'openy_block_expander');
        $info['path'] = $info['theme path'] . '/templates';
      }
    }
  }
}
