<?php

/**
 * @file
 * OpenY digital signage screen content module.
 */

use Drupal\panels\Plugin\DisplayVariant\PanelsDisplayVariant;

/**
 * Implements hook_panels_build_alter().
 */
function openy_digital_signage_screen_content_panels_build_alter(&$build, PanelsDisplayVariant $panels_display) {
  $builder = $panels_display->getBuilder();
  $storage_type = $panels_display->getStorageType();

  $is_panelizer = $builder->getPluginId() == 'ipe' &&
    in_array($storage_type, ['panelizer_default', 'panelizer_field']) &&
    isset($build['#attached']) &&
    isset($build['#attached']['library']) &&
    in_array('panels_ipe/panels_ipe', $build['#attached']['library']);

  if (!$is_panelizer) {
    return;
  }

  /* @var \Drupal\Core\Entity\EntityInterface $entity */
  $entity = $panels_display->getContexts()['@panelizer.entity_context:entity']->getContextValue();
  if ($entity->bundle() != 'screen_content') {
    return;
  }
  $build['#attached']['drupalSettings']['panelizer']['user_permission']['revert'] = FALSE;
  $build['#attached']['drupalSettings']['panelizer']['user_permission']['save_default'] = FALSE;
}
