<?php

/**
 * @file
 * Contains specific features related to the functionality provided by module.
 */

/**
 * Implements hook_cron().
 */
function openy_digital_signage_classes_schedule_cron() {
  /** @var \Drupal\openy_digital_signage_classes_schedule\OpenYClassesScheduleCron $regular_updater */
  $regular_updater = \Drupal::service('openy_digital_signage_classes_schedule.cron');

  $regular_updater->removeOldSessions();
}
