<?php

/**
 * @file
 * Contains specific features related to the functionality provided by module.
 */

use \Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;

/**
 * Implements hook_cron().
 */
function openy_digital_signage_classes_schedule_cron() {
  /* @var \Drupal\openy_digital_signage_classes_schedule\OpenYClassesScheduleCron $regular_updater */
  $regular_updater = \Drupal::service('openy_digital_signage_classes_schedule.cron');

  $regular_updater->removeOldSessions();
}

/**
 * Implements hook_entity_delete().
 */
function openy_digital_signage_classes_schedule_entity_delete(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() != 'openy_ds_classes_session') {
    return;
  }
  /** @var $original_session \Drupal\openy_digital_signage_classes_schedule\Entity\OpenYClassesSession */
  if (!$original_session = $entity->original_session->entity) {
    return;
  }
  $original_session->set('overridden', FALSE);
  $original_session->save();
}

/**
 * Implements hook_entity_operation_alter().
 */
function openy_digital_signage_classes_schedule_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if ($entity->bundle() != 'openy_ds_classes_session') {
    return;
  }

  /* @var \Drupal\openy_digital_signage_classes_schedule\Entity\OpenYClassesSession $entity */
  if ($entity->getSource() != 'manually') {
    // Remove clone and edit options.
    unset($operations['clone']);
    unset($operations['edit']);
    // Add override option.
    $operations['override'] = [
      'title' => t('Override'),
      'url' => Url::fromRoute('entity.openy_ds_classes_session.override', [
        'openy_ds_classes_session' => $entity->id(),
      ]),
      'weight' => 50,
    ];
  }
  elseif ($entity->original_session->entity) {
    // Add override option.
    $operations['original'] = [
      'title' => t('See original'),
      'url' => Url::fromRoute('entity.openy_ds_classes_session.edit_form', [
        'openy_ds_classes_session' => $entity->get('original_session')->target_id,
      ]),
      'weight' => 20,
    ];

  }
}
