<?php

/**
 * @file
 * Contains ymca_link_formatter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ymca_link_formatter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ymca_link_formatter module.
    case 'help.page.ymca_link_formatter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('YMCA Link formatter') . '</p>';
      return $output;

    default:
  }
}

/**
 * Alter the display plugin definitions for a given context.
 *
 * Usually used to remove certain display plugins for specific entities.
 *
 * @param array &$definitions
 *   Remove options from this list if they should not be available for the given
 *   context.
 * @param array $contexts
 *   The provided context, typically an entity.
 */
function ymca_link_formatter_entity_embed_display_plugins_for_context_alter(array &$definitions, array $contexts) {

  if (isset($definitions['entity_reference:entity_reference_label_url'])) {
    $definitions['entity_reference:entity_reference_label_url']['class'] = 'Drupal\ymca_link_formatter\Plugin\Field\FieldFormatter\MenuEntityReferenceLabelFormatter';
    $definitions['entity_reference:entity_reference_label_url']['provider'] = 'ymca_link_formatter';
  }
  if (isset($definitions['entity_reference:file_entity_reference_label_url'])) {
    $definitions['entity_reference:file_entity_reference_label_url']['class'] = 'Drupal\ymca_link_formatter\Plugin\Field\FieldFormatter\FileEntityReferenceLabelFormatter';
    $definitions['entity_reference:file_entity_reference_label_url']['provider'] = 'ymca_link_formatter';
  }

}
