<?php

/**
 * @file
 * Contains openy_upgrade_tool.module.
 */

use Drupal\Core\Url;
use Drupal\openy_upgrade_tool\OpenyUpgradeLogManager;

/**
 * Implements hook_theme().
 */
function openy_upgrade_tool_theme() {
  return [
    'openy_upgrade_log' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for openy_upgrade_log templates.
 *
 * Default template: openy_upgrade_log.html.twig.
 *
 * @param array $variables
 *   An associative array with entity data.
 */
function template_preprocess_openy_upgrade_log(array &$variables) {
  $entity = $variables['elements']['#openy_upgrade_log'];
  $variables['data'] = [
    '#type' => 'html_tag',
    '#tag' => 'pre',
    '#value' => $entity->getYmlData(),
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function openy_upgrade_tool_preprocess_page(&$variables) {
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  $user = \Drupal::currentUser();
  // Show message on admin pages for user with correct permissions.
  if (!($is_admin && $user->hasPermission('edit openy upgrade log entities'))) {
    return;
  }

  // Get upgrade status.
  $status = \Drupal::service('openy_upgrade_log.manager')->getUpgradeStatus();
  if (!$status) {
    // Show message if has unresolved conflicts.
    $url = Url::fromRoute(OpenyUpgradeLogManager::DASHBOARD)->toString();
    \Drupal::messenger()->addMessage(t('
      Website contains unresolved configuration conflicts. 
      Please visit <a href=":url">Upgrade Tool Dashboard</a> page and follow the instructions.
    ', [':url' => $url]), 'warning');
  }
}
