<?php

/**
 * @file
 * Open Y Block Menu routines.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function openy_block_menu_preprocess_field(&$variables) {
  $element = $variables['element'];
  if (!isset($element['#field_name'], $element['#entity_type'], $element['#bundle']) ||
    $element['#field_name'] != 'field_menu_block_links' ||
    $element['#entity_type'] != 'block_content' ||
    $element['#bundle'] != 'menu_block'
  ) {
    return;
  }
  foreach ($variables['items'] as &$item) {
    $item['content']['#options']['set_active_class'] = TRUE;
  }
}
