<?php

/**
 * @file
 * Install, update and uninstall functions for the openy_prgf_fin feature.
 */

/**
 * Remove redundant content bundle.
 */
function openy_prgf_tour_schedule_update_8001() {
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory(drupal_get_path('module', 'openy_prgf_tour_schedule') . '/config/install');
  $config_importer->importConfigs(
    [
      'webform.webform.tour_schedule',
    ]
  );
}
