<?php

/**
 * @file
 * OpenY Media module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function openy_media_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'entity_browser_images_library_embed_form':
    case 'entity_browser_images_library_form':
    case 'entity_browser_documents_library_embed_form':
    case 'entity_browser_documents_library_form':
    case 'entity_browser_videos_library_embed_form':
    case 'entity_browser_videos_library_form':
      $form['#attached']['library'][] = 'openy_media/browser';
      break;
  }
}

/**
 * Preprocess function for grid views of the media library.
 *
 * @param array $variables
 *   Template variables.
 */
function openy_media_preprocess_views_view_grid(array &$variables) {
  switch ($variables['view']->storage->id()) {
    case 'images_library':
    case 'documents_library':
    case 'videos_library':
      foreach ($variables['items'] as &$item) {
        foreach ($item['content'] as &$column) {
          $column['attributes']['data-selectable'] = 'true';
        }
      }
      break;
  }
}
