<?php

/**
 * @file
 * Module file.
 */

use Drupal\Component\Utility\Unicode;
use Drupal\Core\Entity\ContentEntityTypeInterface;

/**
 * Implements hook_theme().
 */
function openy_campaign_theme($existing, $type, $theme, $path) {
  return [
    'openy_campaign_campaign_menu' => [
      'variables' => [
        'base_path' => base_path(),
        'links' => [],
      ],
      'template' => 'openy-campaign-campaign-menu',
    ],
    // Popup templates.
    'openy_campaign_login' => [
      'variables' => [
        'header' => NULL,
        'form' => NULL,
      ],
      'template' => 'openy-campaign-login',
    ],
    'openy_campaign_register' => [
      'variables' => [
        'header' => NULL,
        'form' => NULL,
      ],
      'template' => 'openy-campaign-register',
    ],
    'openy_campaign_activity_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function openy_campaign_cron() {
  // Check if cron was run less then 23 hrs ago and at 2 AM.
  $lastRun = \Drupal::state()->get('openy_campaign.cron_visits_last_run', 0);
  $current = new \DateTime();
  $currentHour = $current->format('H');
  if ((\Drupal::time()->getRequestTime() - $lastRun) < 23 * 60 * 60 || ($currentHour != 2)) {
    return FALSE;
  }

  /** @var \Drupal\openy_campaign\RegularUpdater $regularUpdater */
  $regularUpdater = \Drupal::service('openy_campaign.regular_updater');

  /**
   * Test data:
   *
   * MasterCustomerId - 2052250592, FacilityCardNumber - 4000301612, 2 visits 2017-08-15 and 2017-08-16
   * MasterCustomerId - 2030086900, FacilityCardNumber - 4000044307, 1 visit 2017-08-15
   */
  // Yesterday date - From.
  $dateFrom = new \DateTime();
  //    $dateFrom->setDate(2017, 8, 15)->setTime(0, 0, 0);
  $dateFrom->sub(new \DateInterval('P1D'))->setTime(0, 0, 0);

  // Yesterday date - To.
  $dateTo = new \DateTime();
  //    $dateTo->setDate(2017, 8, 16)->setTime(23, 59, 59);
  $dateTo->sub(new \DateInterval('P1D'))->setTime(23, 59, 59);

  $regularUpdater->createQueue($dateFrom, $dateTo);

  // Update last run.
  \Drupal::state()->set('openy_campaign.cron_visits_last_run', \Drupal::time()->getRequestTime());
}

/**
 * Implements template_preprocess_node().
 */
function openy_campaign_preprocess_node(&$variables, $hook) {
  // Find published Landing page and render it on Campaign page.
  if ($variables['node']->getType() == 'campaign' && $variables['view_mode'] == 'full') {
    // Render the first published Landing page
    $campaignMenuService = \Drupal::service('openy_campaign.campaign_menu_handler');
    $renderLandingPage = $campaignMenuService->getActiveCampaignPage($variables['node']);

    $build = \Drupal::entityTypeManager()->getViewBuilder('node')->view($renderLandingPage);
    $variables['content']['landing_page'] = $build;
  }
}


/**
 * Implements hook_entity_type_build().
 */
function openy_campaign_entity_type_build(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  foreach ($entity_types as &$entity_type) {
    if ($entity_type instanceof ContentEntityTypeInterface) {
      // Override handler by custom implementation.
      $entity_type->setHandlerClass('entity_clone', 'Drupal\openy_campaign\EntityClone\Content\ContentEntityCloneBase');
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Forbid editing some Member entity fields from admin panel.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function openy_campaign_form_openy_campaign_member_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $readonlyFields = [
    'membership_id',
    'personify_id',
    'personify_email'
  ];
  foreach ($readonlyFields as $field) {
    $form[$field]['widget'][0]['value']['#attributes'] = ['readonly' => 'readonly'];
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function openy_campaign_field_widget_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  $fieldName = $context['items']->getName();
  if ($fieldName == 'field_campaign_pages') {
    // Output publishing dates in the backend.
    /** @var \Drupal\node\Entity\Node $node */
    $node = $element['target_id']['#default_value'];
    if (empty($node)) {
      return;
    }

    $publishOn = $unpublishOn = NULL;

    $date_formatter = \Drupal::service('date.formatter');
    if (!empty($node->publish_on->value) && $node->publish_on->value && is_numeric($node->publish_on->value)) {
      $publishOn = $date_formatter->format($node->publish_on->value, 'short');
    }
    if (!empty($node->unpublish_on->value) && $node->unpublish_on->value && is_numeric($node->unpublish_on->value)) {
      $unpublishOn = $date_formatter->format($node->unpublish_on->value, 'short');
    }

    $templateString = '';
    if (!empty($publishOn) && !empty($unpublishOn)) {
      $templateString = 'active from <i>@publish_on</i> to <i>@unpublish_on</i>';
    }
    else if (empty($publishOn) && !empty($unpublishOn)) {
      $templateString = 'active until <i>@unpublish_on</i>';
    }
    else if (!empty($publishOn) && empty($unpublishOn)) {
      $templateString = 'active since <i>@publish_on</i>';
    }

    $message = t($templateString, [
      '@publish_on' => $publishOn,
      '@unpublish_on' => $unpublishOn,
    ]) . ' <a href="' . $node->url('edit-form') . '">' . t('Edit page') . '</a>';

    $element['#suffix'] = '<div class="publishing-dates">' . $message . '</div>';
  }

}

/**
 * Clean email from Personify.
 *
 * @param string $email
 *   Email.
 *
 * @return string
 *   Email.
 */
function cleanPersonifyEmail($email) {
  $email = Unicode::strtolower($email);
  if (Unicode::substr($email, -1, 1) == '.') {
    $email = Unicode::substr($email, 0, Unicode::strlen($email) - 1);
  }
  if (Unicode::substr($email, 0, 1) == '/') {
    $email = Unicode::substr($email, 1, Unicode::strlen($email));
  }

  return $email;
}
