<?php

/**
 * @file
 * Module file for views_infinite_scroll.
 */

use Drupal\Core\Url;
use Drupal\Core\Template\Attribute;
use Drupal\views_infinite_scroll\Plugin\views\pager\InfiniteScroll;

/**
 * Implements hook_preprocess_views_infinite_scroll_pager().
 */
function views_infinite_scroll_preprocess_views_infinite_scroll_pager(&$vars) {
  // The important parts we needed lifted wholesale from
  // template_preprocess_views_mini_pager().
  global $pager_page_array, $pager_total;
  $element = $vars['element'];
  $parameters = $vars['parameters'];
  if ($pager_page_array[$element] < ($pager_total[$element] - 1)) {
    $options = array(
      'query' => pager_query_add_page($parameters, $element, $pager_page_array[$element] + 1),
    );
    $vars['items']['next']['href'] = Url::fromRoute('<current>', [], $options);
  }
  $vars['#cache']['contexts'][] = 'url.query_args';
  $vars['attributes'] = new Attribute([
    'class' => ['js-pager__items', 'pager'],
    'data-drupal-views-infinite-scroll-pager' => $vars['options']['automatically_load_content'] ? 'automatic' : TRUE,
  ]);

}

/**
 * Implements hook_preprocess_views_view().
 */
function views_infinite_scroll_preprocess_views_view(&$vars) {
  $view = $vars['view'];
  if ($view->getDisplay()->isPagerEnabled() && !empty($vars['rows'])) {
    $pager = $view->getPager();
    if ($pager && $pager instanceof InfiniteScroll) {
      $vars['rows']['#theme_wrappers'] = ['container'];
      $vars['rows']['#attributes'] = [
        'data-drupal-views-infinite-scroll-content-wrapper' => TRUE,
        'class' => [
          'views-infinite-scroll-content-wrapper',
          'clearfix',
        ],
      ];
    }
  }
}
