<?php

/**
 * @file
 * Contains openy_prgf_featured_highlights.module.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function openy_prgf_featured_highlights_theme() {
  return [
    'paragraph__featured_highlights__default' => [
      'base hook' => 'paragraph',
    ],
    'openy_featured_highlights_block' => [
      'render element' => 'elements',
      'template' => 'openy-featured-highlights-block',
    ],
    'openy_basic_block' => [
      'render element' => 'elements',
      'template' => 'openy-basic-block',
    ],
    'openy_simple_block' => [
      'render element' => 'elements',
      'template' => 'openy-simple-block',
    ],
    'openy_date_block' => [
      'render element' => 'elements',
      'template' => 'openy-date-block',
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph().
 */
function openy_prgf_featured_highlights_preprocess_paragraph(&$variables) {
  /** @var Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];
  if ($paragraph->bundle() != 'featured_highlights') {
    return;
  }
  foreach (Element::children($variables['content']['field_prgf_block_ref_unlim']) as $key) {
    if (!isset($variables['content']['field_prgf_block_ref_unlim'][$key]['#block_content'])) {
      continue;
    }
    /** @var Drupal\block_content\Entity\BlockContent $block */
    $block = $variables['content']['field_prgf_block_ref_unlim'][$key]['#block_content'];
    switch ($block->bundle()) {
      case 'featured_highlights_block':
        $variables['content']['field_prgf_block_ref_unlim'][$key]['#theme'] = 'openy_featured_highlights_block';
        break;
      case 'basic_block':
        $variables['content']['field_prgf_block_ref_unlim'][$key]['#theme'] = 'openy_basic_block';
        break;
      case 'simple_block':
        $variables['content']['field_prgf_block_ref_unlim'][$key]['#theme'] = 'openy_simple_block';
        break;
      case 'date_block':
        $variables['content']['field_prgf_block_ref_unlim'][$key]['#theme'] = 'openy_date_block';
        break;
    }
  }
}
