<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements template_preprocess_field().
 */
function openy_field_hours_preprocess_field(&$variables, $hook) {
  // Hide labels for some fields.
  $field_types = [
    'openy_field_holiday_hours',
    'openy_field_custom_hours',
  ];
  if (in_array($variables['field_type'], $field_types)) {
    if (empty($variables['items'][0]['content']['#rows'])) {
      $variables['label_hidden'] = TRUE;
    }
  }
}
