<?php

/**
 * @file
 * Contains openy_hb_override_example module hooks.
 */

/**
 * Implements hook_preprocess_page().
 *
 * Example how to override plugin settings.
 *
 * Most home branch plugins has front-end and back-end part.
 * Back-end part provide some settings, that can be used on front-end, for
 * example - \Drupal\openy_home_branch\Plugin\HomeBranchLibrary\HBLocSelectorBranchPage.
 * See getLibrarySettings() method, it provide selector and text, that used
 * in openy_home_branch/js/hb-plugins/hb-loc-selector-branch-page.js
 *
 * Those settings attached to drupalSettings, so we can override this in
 * hook_preprocess.
 *
 * Recommended to use attachHbLibrarySettings() method from service
 * 'plugin.manager.home_branch_library'.
 */
function openy_hb_override_example_preprocess_page(array &$variables) {
  if (\Drupal::hasService('plugin.manager.home_branch_library')) {
    $hb_plugin_service = \Drupal::service('plugin.manager.home_branch_library');
    $hb_plugin_service->attachHbLibrarySettings($variables, 'hb_loc_selector_branch_page', [
      // Here we can change selector in case it different in custom theme.
      'placeholderSelector' => '.openy-branch-selector',
      // Also we can change text, that displayed in component markup.
      'selectedText' => t('Selected'),
      'notSelectedText' => t('Set Home Branch'),
    ]);
  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function openy_hb_override_example_preprocess_paragraph(&$variables) {
  if ($variables['paragraph'] && $variables['paragraph']->getType() == 'prgf_location_finder') {
    // Add js customization for hb_location_finder plugin.
    // @see openy_hb_override_example/js/hb-loc-finder-override.js
    $variables['#attached']['library'][] = 'openy_hb_override_example/location_finder_override';
  }
}
