<?php
/**
 * @file Open Y Node Branch module file.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_presave().
 */
function openy_loc_branch_entity_presave(EntityInterface $entity) {
  if ($entity->getEntityTypeId() !== 'node' || $entity->getType() !== 'branch' || !Drupal::moduleHandler()->moduleExists('rh_node')) {
    return;
  }

  // Hide branch node pages when comming soon is checked, else show.
  if (!empty($entity->field_location_state->getValue()) && is_array($entity->field_location_state->getValue())) {
    $location_state = $entity->field_location_state->get(0)->getValue();
    if (key_exists('value', $location_state) && $location_state['value'] === 1) {
      $entity->rh_action->setValue(['value' => 'page_not_found']);
    }
    elseif (!empty($entity->rh_action->getValue()) && is_array($entity->rh_action->getValue()) && $entity->rh_action->get(0)->getValue() === ['value' => 'page_not_found']) {
      $entity->rh_action->setValue(['value' => 'bundle_default']);
    }
  }
}
