<?php

/**
 * @file
 * Adds a legend of event types.
 */

/**
 * Implements hook_theme().
 */
function fullcalendar_legend_theme($existing, $type, $theme, $path) {
  return array(
    'fullcalendar_legend' => array(
      'variables' => array('types' => NULL),
      'file' => 'fullcalendar_legend.theme.inc',
    ),
  );
}

/**
 * Implements hook_preprocess_block().
 */
function fullcalendar_legend_preprocess_block(&$variables) {
  if ($variables['configuration']['module'] == 'fullcalendar_legend') {
    $variables['attributes']['class'][] = 'fullcalendar-legend';
  }
}
