# Pull gems from RubyGems
source 'https://rubygems.org'

# ~> Refers to all versions of the given gem on the current full version number, so it will be able to use any version of Compass Aurora until Compass Aurora$
gem 'toolkit', '~>1.0.0'
gem 'sass', '~> 3.4.9'
gem 'breakpoint', '~> 2.5.0'
gem 'compass-normalize', '~>1.4.3'
gem 'css_parser', '~>1.3.4'

# Now that you're using Bundler, you need to run `bundle exec compass watch` instead of simply `compass watch`.
