<?php

/**
 * @file
 * Contains openy_prgf_amenities.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function openy_prgf_amenities_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (($form['#id'] == 'views-exposed-form-branches-default') ||
     ($form['#id'] == 'views-exposed-form-location-by-amenities-block-1')) {
    $query = Drupal::entityQuery('taxonomy_term')
      ->condition('vid', 'amenities')
      ->sort('name');
    $results = $query->execute();
    $amenities = \Drupal::service('entity_type.manager')
      ->getStorage('taxonomy_term')
      ->loadMultiple($results);
    $amenities_view = [];
    foreach ($amenities as $key => $amenity) {
      $amenities_view[$key] = \Drupal::service('entity.manager')
        ->getViewBuilder('taxonomy_term')
        ->view($amenity, 'icon');
    }
    foreach ($form['field_location_amenities_target_id']['#options'] as $key => $option) {
      $form['field_location_amenities_target_id']['#options'][$key] =
        \Drupal::service('renderer')->renderRoot($amenities_view[$key]);
    }
  }
}
