<?php
/**
 * @file
 * Install and uninstall functions for the OpenY Demo Node News.
 */

/**
 * Implements hook_install().
 *
 */
function openy_demo_nnews_install() {
//  $importer = \Drupal::service('openy_migrate.importer');
//  $importer->import('openy_demo_lp_paragraph_news_small_banner');
//  $importer->import('openy_demo_lp_paragraph_news_posts_listing');
//  $importer->import('openy_demo_news_landing');
//  $importer->import('openy_demo_menu_link_main_news');
}
