@openy @api
Feature: Taxonomy demo content
  I want to make sure that demo taxonomy are present.

  Background: Login as admin
    Given I am logged in as a user with the "Administrator" role

  Scenario: See demo taxonomy vocabularies
    Given I go to "/admin/structure/taxonomy"
    And I should see "Amenities"
    And I should see "Area"
    And I should see "Blog Category"
    And I should see "Color"
    And I should see "Facility Type"

  Scenario: See demo Amenities taxonomy
    Given I go to "/admin/structure/taxonomy/manage/amenities/overview"
    And I should see "Adaptive programs"
    And I should see "Adult enrichment programs"
    And I should see "After school child care"
    And I should see "Child watch"
    And I should see "Community garden"
    And I should see "Community health"
    And I should see "Day camp"
    And I should see "Family pool/splash pad"
    And I should see "Group exercise classes"
    And I should see "Gymnasium"
    And I should see "Hot tub"
    And I should see "Indoor pool"
    And I should see "Indoor track"
    And I should see "Meeting rooms"
    And I should see "Outdoor pool"
    And I should see "Outdoor track"
    And I should see "Personal training"
    And I should see "Playground"
    And I should see "Racquetball/handball courts"
    And I should see "Sauna"
    And I should see "Steam room"
    And I should see "Strength/cardio equipment"
    And I should see "Swim lessons"
    And I should see "Teen programs"
    And I should see "YMCA children’s academy"
    And I should see "Youth enrichment"

  Scenario: See demo Area taxonomy
    Given I go to "/admin/structure/taxonomy/manage/area/overview"
    And I should see "Auburn"
    And I should see "Beacon Hill"
    And I should see "Bellevue"
    And I should see "Bothell"
    And I should see "Burien"
    And I should see "Capitol Hill and Central District"
    And I should see "Edmonds"
    And I should see "Federal Way"
    And I should see "Kenmore"
    And I should see "Lake Forest Park"
    And I should see "Mountlake Terrace"
    And I should see "Newcastle"
    And I should see "North Bend"
    And I should see "Shoreline"
    And I should see "Wallingford"

  Scenario: See demo Blog Category taxonomy
    Given I go to "/admin/structure/taxonomy/manage/blog_category/overview"
    And I should see "Adults"
    And I should see "Community Outreach"
    And I should see "Family"
    And I should see "General Wellness"
    And I should see "Healthy Eating"
    And I should see "Kids & Teens"
    And I should see "Outdoor"
    And I should see "Personal Y Stories"
    And I should see "Philanthropy"
    And I should see "Physical Activities"
    And I should see "Seniors"
    And I should see "Social Services"
    And I should see "Volunteer"
    And I should see "Y Events"
    And I should see "Y News"

  Scenario: See demo Color taxonomy
    Given I go to "/admin/structure/taxonomy/manage/color/overview"
    And I should see "Black"
    And I should see "Blue"
    And I should see "Brown"
    And I should see "Dark blue"
    And I should see "Dark green"
    And I should see "Dark magenta"
    And I should see "Green"
    And I should see "Grey"
    And I should see "Light blue"
    And I should see "Light green"
    And I should see "Orange"
    And I should see "Pink"
    And I should see "Purple"
    And I should see "Red"
    And I should see "Sky blue"
    And I should see "White"
    And I should see "Yellow"

  Scenario: See demo Facility Type taxonomy
    Given I go to "/admin/structure/taxonomy/manage/facility_type/overview"
    And I should see "After School Site"
    And I should see "Before & After School Care"
    And I should see "Branch Facility"
    And I should see "Day Camp Site"
    And I should see "Early Learning Center"
    And I should see "Horse Camp"
    And I should see "Preschool Child Care"
