<?php

/**
 * @file
 * Install, update/uninstall functions for the openy_prgf_location_by_amenities.
 */

/**
 * Implements hook_uninstall().
 */
function openy_prgf_location_by_amenities_uninstall() {
  $modules_manager = \Drupal::service('openy.modules_manager');
  $modules_manager->removeEntityBundle('paragraph', 'paragraphs_type', 'location_filter_by_amenities');
  $modules_manager->removeModuleConfigs('openy_prgf_location_by_amenities');
}
