<?php

/**
 * @file
 * Testing Slick.
 */

/**
 * Implements hook_theme().
 */
function slick_test_theme() {
  return ['slick_test' => ['render element' => 'element']];
}

/**
 * Prepares variables for slick-test.html.twig templates.
 */
function template_preprocess_slick_test(&$variables) {
  $element = $variables['element'];

  $variables['content'] = $element['#children'];
  $variables['settings'] = isset($element['#settings']) ? $element['#settings'] : [];
}

/**
 * Implements hook_slick_skins_info().
 */
function slick_test_slick_skins_info() {
  return '\Drupal\slick_test\SlickSkinTest';
}

if (!function_exists('video_embed_media_media_bundle_insert')) {

  /**
   * Dummy function.
   */
  function video_embed_media_media_bundle_insert() {
    // Empty block to satisfy coder.
  }

}

