<?php

/**
 * @file
 * OpenY Data Layer module file.
 */

/**
 * Implements hook_datalayer_meta_alter().
 */
function openy_datalayer_datalayer_meta_alter(&$properties) {
  // Override module norm in all cases.
//  unset($properties['entityUid']);

  // Specific situation alteration...
  if ($obj = _datalayer_menu_get_any_object()) {
    // && in_array(array('my_bundle', 'my_nodetype'), $obj->type)
    if ($obj->getEntityTypeId() === 'node') {
      // Remove author names on some content type.
//      if ($key = array_search('name', $properties)) {
//        unset($properties[$key]);
//      }
//      if ($key = array_search('uid', $properties)) {
//        unset($properties[$key]);
//      }
    }
//    elseif ($obj->type === 'my_entity_type') {
//      // Remove some property on some entity type.
//      if ($key = array_search('my_property', $properties)) {
//        unset($properties[$key]);
//      }
//    }
  }
}