<?php

/**
 * @file
 * Open Y Data Layer module file.
 */

/**
 * Implements hook_datalayer_meta_alter().
 */
function openy_datalayer_datalayer_meta_alter(&$properties) {
  if ($obj = _datalayer_menu_get_any_object()) {
    if ($obj->getEntityTypeId() === 'node') {
      // Remove author names on some content type.
      if ($key = array_search('name', $properties)) {
        unset($properties[$key]);
      }
      if ($key = array_search('uid', $properties)) {
        unset($properties[$key]);
      }
    }
  }
}
