<?php

/**
 * @file
 * Module file.
 */

/**
 * Run sync service.
 *
 * @param string $name
 *   Service name.
 * @param string $method
 *   Method name.
 *
 * @throws \Exception
 */
function ymca_sync_run($name, $method) {
  $active = \Drupal::config('ymca_sync.settings')->get('active_syncers');
  // Run only active syncers.
  if (!in_array($name, $active)) {
    return;
  }

  $service = \Drupal::service($name);
  if (!$service) {
    throw new Exception('Failed to load specified service');
  }

  $lock = \Drupal::lock();
  if ($lock->acquire($name, 250.0)) {
    $service->{$method}();
    $lock->release($name);
  }
  else {
    $msg = 'Lock "%name" is still working. Exit.';
    Drupal::logger('ymca_sync')->info(
      $msg,
      [
        '%name' => $name,
      ]
    );
  }
}
