<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements template_preprocess_field().
 */
function ymca_hours_preprocess_field(&$variables, $hook) {
  // Hide labels for some fields.
  $field_types = [
    'ymca_holiday_hours',
    'ymca_custom_hours',
  ];
  if (in_array($variables['field_type'], $field_types)) {
    if (empty($variables['items'][0]['content']['#rows'])) {
      $variables['label_hidden'] = TRUE;
    }
  }
}
