<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements template_preprocess_field().
 */
function ymca_hours_preprocess_field(&$variables, $hook) {
  if ($variables['field_type'] == 'ymca_holiday_hours') {
    if (empty($variables['items'][0]['content']['#rows'])) {
      $variables['label_hidden'] = TRUE;
    }
  }
}
