<?php
/**
 * @file OpenY Paragraph classes listing module file.
 */

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function openy_prgf_classes_listing_form_views_exposed_form_alter(&$form, FormStateInterface $form_state) {
  if ($form['#id'] == 'views-exposed-form-classes-listing-search-form') {
    $user_input = $form_state->getUserInput();

    // Pre-define context.
    if ($node = \Drupal::routeMatch()->getParameter('node')) {
      if ($node->hasField('field_category_program')) {
        $user_input['category'] = $node->id();
        if (!empty($node->field_category_program->target_id)) {
          $user_input['program'] = $node->field_category_program->target_id;
        }
      }
      $form_state->setUserInput($user_input);
    }
  }
}
