<?php

/**
 * @file
 * Contains openy_prgf_faq specific functions.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view().
 */
function openy_prgf_faq_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->getEntityTypeId() == 'paragraph' && $entity->bundle() == 'faq') {
    $build['#attached']['library'][] = 'openy_prgf_faq/paragraph';
  }
}
