<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function openy_prgf_event_listing_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $storage = $form_state->getStorage();
  /** @var \Drupal\views\Entity\View $view */
  $view = $storage['view'];
  if (empty($view)) {
    return;
  }

  // Add placeholder to views exposed form
  if ($view->id() == 'listing_event_posts' && $view->current_display == 'events_listing_block') {
    $form['combine']['#attributes']['placeholder'] = t('Search the events...');
  }
}