<?php

/**
 * @file
 * Contains specific features related to the functionality provided by module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function ymca_retention_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-ymca-members-ymca-members-list') {
    $form['mail']['#attributes']['placeholder'] = t('Email');
    $date = new \DateTime();
    $date->setTime(0, 0, 0);
    $form['created_from']['#attributes']['placeholder'] = $date->format('Y-m-d H:i:s');
    $date->add(new \DateInterval('P1D'));
    $form['created_to']['#attributes']['placeholder'] = $date->format('Y-m-d H:i:s');
  }
}

/**
 * Implements hook_theme().
 */
function ymca_retention_theme($existing, $type, $theme, $path) {
  return [
    'ymca_retention_registration_form' => [
      'render element' => 'form',
    ],
    'ymca_retention_login_form' => [
      'render element' => 'form',
    ],
    'ymca_retention_track_activity_form' => [
      'render element' => 'form',
    ],
    'ymca_retention_intro' => [
      'variables' => [
        'content' => NULL,
      ],
      'template' => 'ymca-retention-intro',
    ],
    'ymca_retention_leaderboard' => [
      'variables' => [
        'base_path' => base_path(),
      ],
      'template' => 'ymca-retention-leaderboard',
    ],
    'ymca_retention_navigation' => [
      'variables' => [
        'content' => NULL,
      ],
      'template' => 'ymca-retention-navigation',
    ],
    'ymca_retention_member_info' => [
      'variables' => [
        'member' => [],
      ],
      'template' => 'ymca-retention-member-info',
    ],
    'ymca_retention_slider' => [
      'variables' => [],
      'template' => 'ymca-retention-slider',
    ],
    'ymca_retention_registration_confirmation' => [
      'variables' => [
        'member' => [],
      ],
      'template' => 'ymca-retention-registration-confirmation',
    ],
  ];
}
