<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme().
 */
function openy_calc_theme() {
  return [
    'form_element_membership_type' => [
      'render element' => 'element',
    ],
    'openy_calc_form_header' => [
      'variables' => [
        'steps' => [],
      ],
      'template' => 'openy-calc-form-header',
    ],
    'openy_calc_form_summary' => [
      'variables' => [
        'result' => [],
        'map' => [],
      ],
      'template' => 'openy-calc-form-summary',
    ],
  ];
}

/**
 * Preprocess variables.
 */
function template_preprocess_form_element_membership_type(&$variables) {
  template_preprocess_form_element($variables);
  $element = &$variables['element'];
  $variables['element_variables'] = $element['#element_variables'];
}

/**
 * Preprocess variables.
 */
function openy_calc_preprocess_fieldset(&$variables) {
  /** @var $legend_span \Drupal\Core\Template\Attribute */
  if (isset($variables['element']['#type']) && $variables['element']['#type'] == 'calc_radios') {
    $legend_span = $variables['legend_span']['attributes'];
    $legend_span->setAttribute('tabindex', '0');
  }
}
