<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_page_attachments().
 */
function ymca_personify_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'ymca_personify/personify';
}

/**
 * Implements hook_theme().
 */
function ymca_personify_theme() {
  return [
    'ymca_childcare_payment_history' => [
      'variables' => [
        'content' => [],
      ],
    ],
    'ymca_childcare_payment_history__pdf__body' => [
      'variables' => [
        'content' => [],
      ],
    ],
    'ymca_childcare_payment_history__pdf__footer' => [
      'variables' => [],
    ],
  ];
}
