<?php

/**
 * @file
 * Module file for page_example_module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

const LNDR_BASE = 'https://www.lndr.co/';
const LNDR_API_GET_PROJECT = 'https://www.lndr.co/v1/projects';
const LNDR_API_VALIDATE_TOKEN = 'https://www.lndr.co/v1/validate_token';

/**
 * Implements hook_help().
 *
 */
function lndr_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'lndr_config':
      // Help text for the simple page registered for this path.
      return t('We help Lndr here');
  }
}

/**
 * Implements hook_cron().
 *
 */
function lndr_cron() {
  $controller = new \Drupal\lndr\Controller\LndrController();
  $controller->sync_path();
}
