<?php

DEFINE('CAMPAIGN_THEME', 'openy_campaign_theme');
DEFINE('OPENY_THEME', 'openy_rose');

DEFINE('CAMPAIGN_BASIC_PALETTE', 'purpleorchid');
DEFINE('CAMPAIGN_COLORS_CSS_FILE', 'campaign_colors');
DEFINE('CAMPAIGN_MAIN_COLORS', ['mainlight', 'mainmedium', 'maindark']);

/**
 * Implements hook_theme().
 */
function openy_campaign_color_theme() {
  return [
    'openy_campaign_color_scheme_form' => [
      'render element' => 'form',
    ],
  ];
}

function openy_campaign_color_add_color_switcher() {

}
/**
 * Implements hook_form_FORM_ID_alter().
 */
function openy_campaign_color_form_node_campaign_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  openy_campaign_color_form_node_campaign_palette($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function openy_campaign_color_form_node_campaign_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  openy_campaign_color_form_node_campaign_palette($form, $form_state);
}

function openy_campaign_color_form_node_campaign_palette(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  if (color_get_info(OPENY_THEME) && function_exists('gd_info')) {
    $form['color'] = [
      '#type' => 'details',
      '#title' => t('Color scheme'),
      '#open' => TRUE,
      '#weight' => -1,
      '#attributes' => ['id' => 'openy_campaign_color_color_scheme_form'],
      '#theme' => 'openy_campaign_color_scheme_form',
    ];
    $form['color'] += openy_campaign_color_scheme_form($form, $form_state);

    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'openy_campaign_color_color_scheme_form_submit';
      }
    }
  }
}
/**
 * Form constructor for the color configuration form for a particular theme.
 *
 * @param $theme
 *   The machine name of the theme whose color settings are being configured.
 *
 * @see color_scheme_form_validate()
 * @see color_scheme_form_submit()
 */
function openy_campaign_color_scheme_form($complete_form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $campaignPalette = NULL;
  if ($form_state->getFormObject() instanceof \Drupal\Core\Entity\EntityForm) {
    $campaign = $form_state->getFormObject()->getEntity();
    $campaignPalette = $campaign->field_campaign_palette->value;
  }

  $info = color_get_info(OPENY_THEME);
  $color_sets = [];
  $schemes = [];
  foreach ($info['schemes'] as $key => $scheme) {
    $color_sets[$key] = $scheme['title'];
    $schemes[$key] = $scheme['colors'];
    $schemes[$key] += $info['schemes']['default']['colors'];
  }

  // Add scheme selector.
  $palette = color_get_palette(OPENY_THEME, FALSE);

  $form['scheme'] = [
    '#type' => 'select',
    '#title' => t('Color set'),
    '#options' => $color_sets,
    '#default_value' => $campaignPalette,
    '#attached' => [
      'library' => [
        'openy_campaign_color/drupal.openy_campaign_color',
      ],
      // Add custom JavaScript.
      'drupalSettings' => [
        'color' => [
          'reference' => $palette,
          'schemes' => $schemes,
        ]
      ],
    ],
  ];

  // Add palette fields. Use the configuration if available.
  $names = $info['fields'];
  $form['palette']['#tree'] = TRUE;
  foreach ($schemes[$campaignPalette] as $name => $value) {
    if (isset($names[$name]) && in_array($name, CAMPAIGN_MAIN_COLORS)) {
      $form['palette'][$name] = [
        '#type' => 'textfield',
        '#title' => $names[$name],
        '#value_callback' => 'color_palette_color_value',
        '#default_value' => $value,
        '#size' => 8,
        '#attributes' => ['disabled' => 'disabled']
      ];
    }
  }
  $form['theme'] = ['#type' => 'value', '#value' => OPENY_THEME];

  return $form;
}

function openy_campaign_color_color_scheme_form_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  /** @var Drupal\node\Entity\Node $entity */
  if ($entity = $form_state->getFormObject()->getEntity()) {
    $entity->set('field_campaign_palette', $form_state->getValue('scheme'));
    $entity->save();
  }
}

function openy_campaign_color_rebuild() {
  // Build CSS files for each color scheme.

  // Read basic CSS file.
  $cssPath = DRUPAL_ROOT . '/' . drupal_get_path('theme', CAMPAIGN_THEME) . '/css/styles.css';
  $cssData = file_get_contents($cssPath);

  // Get list of all possible colors palettes.
  $info = color_get_info(OPENY_THEME);
  $colorSets = [];
  $schemes = [];
  foreach ($info['schemes'] as $key => $scheme) {
    $colorSets[$key] = $scheme['title'];
    $schemes[$key] = $scheme['colors'];
    $schemes[$key] += $info['schemes']['default']['colors'];
  }

  // Basic colors will be used for the replacement.
  $basicColorSet = [];
  foreach ($schemes[CAMPAIGN_BASIC_PALETTE] as $key => $color) {
    if (!in_array($key, CAMPAIGN_MAIN_COLORS)) {
      continue;
    }
    // Lowercase the colors.
    $basicColorSet[$key] = strtolower($color);

    // Replace 3digits colors by full values.
    if (strlen($color) == 4) {
      $basicColorSet[$key] = $color . ltrim($color, '#');
    }
  }
  $basicColorSet = array_flip($basicColorSet);

  // Parse all colors from the basic CSS file..
  $re = '/(#[0-9a-f]{6}|#[0-9a-f]{3})/i';
  preg_match_all($re, $cssData, $matches, PREG_SET_ORDER, 0);

  $basicCssColors = [];
  foreach ($matches as $match) {
    $color = strtolower($match[0]);
    // Replace 3digits colors by full values.
    if (strlen($color) == 4) {
      $color = $color . ltrim($color, '#');
    }
    $basicCssColors[] = $color;
  }
  $basicCssColors = array_unique($basicCssColors);

  // Generate CSS files for each palette.
  foreach ($schemes as $key => $scheme) {
    $newCss = $cssData;
    foreach ($basicCssColors as $color) {
      // Skip colors out of the main palette.
      if (!isset($basicColorSet[$color])) {
        continue;
      }
      $colorKey = $basicColorSet[$color];
      $newCss = str_replace($color, $scheme[$colorKey], $newCss);
    }
    file_unmanaged_save_data($newCss, 'public://' . CAMPAIGN_COLORS_CSS_FILE . '_' . $key . '.css', FILE_EXISTS_REPLACE);
  }
}

function openy_campaign_color_css_alter(&$css, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {
  // Get campaign node from current page URL
  /** @var \Drupal\node\Entity\Node $campaign */
  $campaign = \Drupal::service('openy_campaign.campaign_menu_handler')->getCampaignNodeFromRoute();
  if (empty($campaign)) {
    return;
  }

  $route = \Drupal::routeMatch()->getRouteObject();

  $is_admin = FALSE;
  if (!empty($route)) {
    $is_admin_route = \Drupal::service('router.admin_context')->isAdminRoute($route);
    $has_node_operation_option = $route->getOption('_node_operation_route');
    $is_admin = ($is_admin_route || $has_node_operation_option);
  }
  else {
    $current_path = \Drupal::service('path.current')->getPath();
    if(preg_match('/node\/(\d+)\/edit/', $current_path, $matches)) {
      $is_admin = TRUE;
    }
    elseif(preg_match('/taxonomy\/term\/(\d+)\/edit/', $current_path, $matches)) {
      $is_admin = TRUE;
    }
  }

  if ($is_admin) {
    return;
  }

  $cssFile = 'public://' . CAMPAIGN_COLORS_CSS_FILE . '_' . $campaign->field_campaign_palette->value . '.css';
  $css[$cssFile] = [
    'weight' => 1000,
    'group' => 100,
    'type' => 'file',
    'data' => $cssFile,
    'media' => 'all',
    'preprocess' => 1,
    'browsers' => [
      'IE' => 1,
      '!IE' => 1
    ]
  ];

}
