<?php

/**
 * @file
 * Contains openy_branch module hooks.
 */

use Drupal\node\NodeInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\openy_branch\Utility\UpdatesQueueProvisioner;

/**
 * Implements hook_theme().
 */
function openy_schedules_theme() {
  return [
    'openy_schedules_main' => [
      'variables' => [
        'title' => '',
        'content' => [],
      ],
    ],
    'openy_schedules_main_class' => [
      'variables' => [
        'title' => '',
        'content' => [],
      ],
    ],
    'openy_branch_hours_block' => [
      'variables' => [
        'branch_hours' => [],
      ],
    ],
    'openy_schedules_alerts_block' => [
      'variables' => [
        'alerts' => [],
      ],
    ],
    'openy_schedules_subcategory_filters' => [
      'variables' => [
        'filters' => [],
      ],
      'template' => 'openy-schedules-subcategory-filters',
    ],
  ];
}
