<?php

/**
 * @file
 * Main file for the Open Y Node Blog module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\State\StateInterface;

/**
 * Implements hook_form_alter().
 */
function openy_node_blog_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_blog_edit_form' || $form_id == 'node_blog_form') {
    $visible = [
      'visible' => [
        [
          'select[name="field_blog_style"]' => ['value' => 'color'],
        ],
      ],
    ];
    $form['field_blog_color']['widget']['#states'] = $visible;     
    $form['field_blog_text_color']['widget']['#states'] = $visible;
  }
}
