<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\contact\MessageInterface;

/**
 * Implements hook_theme().
 */
function ymca_membership_theme($existing, $type, $theme, $path) {
  return [
    'membership_page' => [
      'variables' => [
        'assets' => [],
        'assets_path' => '',
        'block_form_fee' => '',
        'block_cost' => '',
        'block_become_a_member' => '',
        'block_ready_started' => '',
        'form' => '',
      ],
      'template' => 'membership-page',
    ],
    'membership_thank_you' => [
      'variables' => [
        'location' => '',
        'submission' => '',
        'block_whats_next' => '',
        'block_special_offer' => '',
        'form' => '',
      ],
      'template' => 'membership-thank-you',
    ],
    'datebased_block_with_cl' => [
      'variables' => [
        'content' => '',
      ],
      'template' => 'datebased-block',
    ],
    'membership_mail' => [
      'variables' => [
        'message' => NULL,
        'firstname' => '',
        'location' => [
          'name' => '',
          'address_line1' => '',
          'address_line2' => '',
          'zip' => '',
          'phone' => '',
          'map' => '',
          'link' => '',
        ],
      ],
      'template' => 'membership-mail',
    ],

    'membership_mail_editor' => [
      'variables' => [
        'message' => NULL,
        'firstname' => '',
        'lastname' => '',
        'phone' => '',
        'email' => '',
        'location' => [
          'name' => '',
          'address_line1' => '',
          'address_line2' => '',
          'zip' => '',
          'phone' => '',
          'map' => '',
          'link' => '',
        ],
      ],
      'template' => 'membership-mail-editor',
    ],
    'membership_mail_wrapper' => [
      'variables' => [
        'content_area_1' => '',
        'content_area_2' => '',
        'content_area_3' => '',
        'theme_path' => '',
        'site_path' => '',
        'current_date_month_text_long' => '',
        'current_date_day' => '',
        'current_date_year_long' => '',
      ],
      'template' => 'membership-mail-wrapper',
    ],
  ];
}

/**
 * Implements hook_mail_alter().
 */
function ymca_membership_mail_alter(&$message) {
  if (in_array($message['id'], ['contact_page_mail', 'contact_page_copy'])) {
    if (!empty($message['params']['contact_form']) && $message['params']['contact_form']->id() == 'membership_form') {
      $theme_url = URL::fromUri('base:themes/custom/ymca/img');
      $theme_url->setAbsolute(TRUE);
      $site_url = URL::fromRoute('<front>');
      $site_url->setAbsolute(TRUE);
      $mail_wrapper_build = [
        '#theme' => 'membership_mail_wrapper',
        '#theme_path' => $theme_url,
        '#site_path' => $site_url,
        '#current_date_month_text_long' => date('F'),
        '#current_date_day' => date('j'),
        '#current_date_year_long' => date('Y'),
        '#content_area_1' => [
          '#theme' => 'membership_mail',
          '#message' => $message,
        ],
        '#content_area_2' => '',
        '#content_area_3' => '',
      ];
      $message['subject'] = 'YMCA Membership Inquiry';
      // Output link to the mail is being sent to editors.
      if ($message['id'] == 'contact_page_mail') {
        $url = URL::fromRoute('entity.contact_message.edit_form', [
          'contact_message' => $message['params']['contact_message']->id(),
        ]);
        $url->setAbsolute(TRUE);
        $link = new Link($url->toString(), $url);
        $mail_wrapper_build['#content_area_3']['#markup'] = 'Submission can be found at ' . $link->toString();
        $mail_wrapper_build['#content_area_1']['#theme'] = 'membership_mail_editor';
        /* @var \Drupal\contact\Entity\Message $submission */
        $submission = $message['params']['contact_message'];
        $field_name = \Drupal::config('ymca_membership.config')->get('webform_location_field');
        $location = \Drupal::service('webforms.node_extractor')
          ->extractNode($submission, $field_name, 'location');
        if ($location) {
          $message['subject'] = 'Membership Inquiry - ' . $location->getTitle();
        }
      }
      $message['body'] = [
        \Drupal::service('renderer')->render($mail_wrapper_build),
      ];
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
    }
  }
}

/**
 * Preprocess function.
 */
function ymca_membership_preprocess_membership_mail(&$variables) {
  ymca_membership_preprocess_membership_mail_message($variables);
}

/**
 * Preprocess function.
 */
function ymca_membership_preprocess_membership_mail_editor(&$variables) {
  ymca_membership_preprocess_membership_mail_message($variables);
}

/**
 * Preprocess function.
 */
function ymca_membership_preprocess_membership_mail_message(&$variables) {
  /* @var \Drupal\contact\Entity\Message $submission */
  $submission = $variables['message']['params']['contact_message'];
  $variables['firstname'] = $submission->field_first_name->getValue()[0]['value'];
  $variables['lastname'] = $submission->field_last_name->getValue()[0]['value'];
  $variables['phone'] = $submission->field_phone_number->getValue()[0]['value'];
  $variables['email'] = $submission->field_email_address->getValue()[0]['value'];

  $field_name = \Drupal::config('ymca_membership.config')->get('webform_location_field');
  $location = \Drupal::service('webforms.node_extractor')
    ->extractNode($submission, $field_name, 'location');

  if (!$location) {
    \Drupal::logger('ymca_membership')->alert(t('Unbound prefered Y location value selected.'));
  }
  else {
    $address = $location->field_location->getValue()[0];
    list($line1, $line2) = explode(', ', $address['address_line1'], 2);
    $phone = $location->field_phone->getValue()[0]['value'];

    $map_link = new Link('Map and Directions', URL::fromUri('http://maps.google.com/', [
      'query' => ['q' => $address['address_line1'] . $address['postal_code']],
    ]));

    $options = [
      'attributes' => [
        'target' => '_blank',
      ],
      'query' => [
        'utm_source' => 'YMCA Membership Inquiry',
        'utm_campaign' => 'Registration Welcome',
        'utm_medium' => 'email',
      ],
    ];
    $url = URL::fromUri('entity:node/' . $location->id(), $options);
    $url->setAbsolute(TRUE);
    $more_link = new Link('More about this location', $url);

    $variables['location'] = [
      // TODO: full title should be taken from other field.
      'name' => $location->getTitle(),
      'address_line1' => $line1,
      'address_line2' => $line2,
      'zip' => $address['postal_code'],
      'map' => $map_link,
      'phone' => $phone,
      'link' => $more_link,
    ];
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for contact_form_form().
 */
function ymca_membership_form_contact_message_form_alter(&$form, &$form_state, $form_id) {
  $form['actions']['submit']['#submit'][] = 'ymca_membership_contact_message_redirect_submit';
}

/**
 * Implements hook_form_FORM_ID_alter() for contact_form_edit_form().
 */
function ymca_membership_form_contact_form_edit_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['id']['#default_value']) && $form['id']['#default_value'] == 'membership_form') {
    unset($form['submission_page']);
    unset($form['contact_storage_uri']);
    $special_offer_id = \Drupal::config('ymca_membership.config')->get('thank_you_special_offer_block_id');
    $what_is_next_id = \Drupal::config('ymca_membership.config')->get('thank_you_what_is_next_block_id');
    $special_offer_link = new Link(t('Special Offer'), Url::fromUri('internal:/block/' . $special_offer_id));
    $what_is_next_link = new Link(t('What is next'), Url::fromUri('internal:/block/' . $what_is_next_id));
    $special_offer_link_renderable = $special_offer_link->toRenderable();
    $what_is_next_link_renderable = $what_is_next_link->toRenderable();
    $form['email']['#suffix'] = t('
      <strong>Edit blocks on Thank you page</strong><br/>
      Edit "@special_offer_link" block.<br/>
      Edit "@what_is_next_link" block.',
      array(
        '@special_offer_link' => render($special_offer_link_renderable),
        '@what_is_next_link' => render($what_is_next_link_renderable),
      )
    );
  }
}

/**
 * Implements a Submit Callback for Membership form.
 */
function ymca_membership_contact_message_redirect_submit(&$form, &$form_state) {
  /* @var \Drupal\contact\MessageInterface $contact_message */
  $contact_message = $form_state->getFormObject()->getEntity();
  if ($contact_message->bundle() !== 'membership_form') {
    return;
  }
  $redirect_uri = 'base:membership/thank-you';
  $form_state->setRedirectUrl(Url::fromUri($redirect_uri, [
    'query' => [
      'key' => $contact_message->uuid(),
    ],
  ]));
}

/**
 * Implements hook_webforms_sent_message_alter().
 */
function ymca_membership_webforms_sent_message_alter(&$messages, MessageInterface $message) {
  if ($message->bundle() == 'membership_form') {
    $messages = [];
  }
}
