<?php

/**
 * @file
 * Provides primary Drupal hook implementations.
 *
 * Adds a JavaScript snippet to selected page responses to trigger analytics and
 * other tracking items configured using the Google Tag Manager.
 *
 * @author Jim Berry ("solotandem", http://drupal.org/user/240748)
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Default for matching all items, except listed.
 */
const GOOGLE_TAG_DEFAULT_INCLUDE = 'all_except_listed';

/**
 * Default for only matching listed items.
 */
const GOOGLE_TAG_DEFAULT_EXCLUDE = 'only_listed';

/**
 * Implements hook_help().
 */
function google_tag_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.google_tag':
    case 'google_tag.settings_form':
      return t('<a href=":url">Google Tag Manager</a> is a free service (registration required) to manage the insertion of tags for capturing website analytics.', array(':url' => 'http://www.google.com/tagmanager/'));
  }
}
