<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\openy_block_date\EntityOperations;

/**
 * @file
 * Contains date block module file.
 */

/**
 * Implements hook_ENTITY_TYPE_build_defaults_alter().
 */
function openy_block_date_block_content_build_defaults_alter(array &$build, EntityInterface $entity, $view_mode) {
  $build = \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(EntityOperations::class)
    ->buildDefaultsAlter($build, $entity, $view_mode);
}
