<?php

/**
 * @file
 * Install, update and uninstall functions for the openy_prgf_all_testimonials feature.
 */

/**
 * Update All Testimonials view.
 */
function openy_prgf_all_testimonials_update_8001() {
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory(drupal_get_path('module', 'openy_prgf_all_testimonials') . '/config/install');
  $config_importer->importConfigs(
    [
      'views.view.testimonials',
    ]
  );
}
