<?php
/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme().
 */
function ymca_groupex_theme($existing, $type, $theme, $path) {
  return [
    'groupex_class' => [
      'variables' => [
        'class' => [],
      ],
      'template' => 'groupex-class',
    ],
    'groupex_schedule_day' => [
      'variables' => [
        'classes' => [],
      ],
      'template' => 'groupex-schedule-day',
    ],
    'groupex_schedule_week' => [
      'variables' => [
        'days' => [],
      ],
      'template' => 'groupex-schedule-week',
    ],
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function ymca_groupex_preprocess_node(&$variables) {
  // Pass the form to the schedules page.
  if ($variables['node']->bundle() == 'location' && $variables['view_mode'] == 'schedules') {
    $form = \Drupal::formBuilder()->getForm('Drupal\ymca_groupex\Form\GroupexFormLocation');
    $variables['form_find_classes'] = \Drupal::service('renderer')->render($form, FALSE);
  }

  // Pass the search results to the schedules page.
  if ($variables['node']->bundle() == 'location' && $variables['view_mode'] == 'groupex') {
    $query = \Drupal::request()->query->all();

    // Output refine form.
    $form = \Drupal::formBuilder()->getForm('Drupal\ymca_groupex\Form\GroupexFormLocationRefine', $query);
    $variables['groupex_form_refine'] = \Drupal::service('renderer')->render($form, FALSE);

    // Get classes schedules.
    $fetcher = new \Drupal\ymca_groupex\GroupexScheduleFetcher($query);
    $schedule = $fetcher->getSchedule();

    $results = [
      '#markup' => t('Nothing found...'),
    ];

    // Output schedule by type.
    // @todo Add schedule by location.
    switch ($schedule['type']) {
      case 'day':
        // Check if there is something.
        if (!empty($schedule['classes'])) {
          $results = [
            '#theme' => 'groupex_schedule_day',
            '#classes' => $schedule['classes'],
          ];
        }
        break;

      case 'week':
        // Check if there is something.
        if (!empty($schedule['days'])) {
          $results = [
            '#theme' => 'groupex_schedule_week',
            '#days' => $schedule['days'],
          ];
        }
        break;
    }

    $variables['groupex_search_results'] = \Drupal::service('renderer')->render($results, FALSE);
  }
}
