<?php

/**
 * @file
 * Contains specific features related to the functionality provided by module.
 */

use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\openy_digital_signage_classes_schedule\Entity\OpenYClassesSession;

/**
 * Implements hook_help().
 */
function openy_digital_signage_personify_schedule_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'system.admin_openy_digital_signage_personify_schedule_settings':
      $output = '';
      $output .= '<h3>' . t('Personify settings') . '</h3>';
      $output .= '<p>' . t('Specify locations you want to use for import from Personify. Only selected locations are used to import sessions.') . '</p>';
      $output .= '<p>';
      $output .= t('To configure mapping with personify go to the @url.', [
        '@url' => Link::fromTextAndUrl('Locations Mapping page', Url::fromRoute('view.location_mapping.page_1'))
          ->toString(),
      ]);
      $output .= '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_create().
 */
function openy_digital_signage_personify_schedule_entity_create(EntityInterface $entity) {
  if ($entity->getEntityTypeId() != 'openy_ds_classes_personify_session') {
    return;
  }
}

/**
 * Implements hook_entity_update().
 */
function openy_digital_signage_personify_schedule_entity_update(EntityInterface $entity) {
  if ($entity->getEntityTypeId() != 'openy_ds_classes_personify_session') {
    return;
  }
}

/**
 * Implements hook_entity_delete().
 */
function openy_digital_signage_personify_schedule_entity_delete(EntityInterface $entity) {
  /** @var OpenYClassesSession $entity */
  if ($entity->getEntityTypeId() != 'openy_ds_classes_session') {
    return;
  }
}

/**
 * Implements hook_cron().
 */
function openy_digital_signage_groupex_schedule_cron() {
  /* @var \Drupal\openy_digital_signage_personify_schedule\OpenYSessionsPersonifyCron $cron_service */
  $cron_service = \Drupal::service('openy_digital_signage_personify_schedule.cron');

  $cron_service->importSessions();
}
