<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_libraries_info().
 */
function tango_card_libraries_info() {
  $libraries['tango_card'] = array(
    'title' => t('Tango Card'),
    'version' => '1.0.0',
    'files' => array(
      'php' => array(
        'src/TangoCardAppModeInvalidException.php',
        'src/TangoCardBase.php',
        'src/TangoCard.php',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_entity_operation().
 */
function tango_card_entity_operation(EntityInterface $entity) {
  $operations = array();

  if ($entity->getEntityTypeId() == 'tango_card_account') {
    $operations['fund'] = array(
      'title' => t('Fund'),
      'weight' => 0,
      'url' => $entity->toUrl('fund-form'),
    );
  }

  return $operations;
}
