<?php

/**
 * @file
 * OpenY User install file.
 */

/**
 * Add Editor and Contributor roles.
 */
function openy_user_update_8001() {
  $config_dir = drupal_get_path('module', 'openy_user') . '/config/install';
  $config_importer = \Drupal::service('openy_upgrade_tool.importer');
  $config_importer->setDirectory($config_dir);
  $config_importer->importConfigs([
    'user.role.contributor',
    'user.role.editor',
  ]);
}
