<?php

/**
 * @file
 * Local Fonts install file.
 */

/**
 * Implements hook_install().
 */
function local_fonts_install() {
  module_set_weight('local_fonts', 10);
  drupal_set_message(t('You may now install your own custom fonts. Remember to follow the EULA for any given font.'));
}

/**
 * Implements hook_uninstall().
 */
function local_fonts_uninstall() {
  fontyourface_delete('local_fonts');
}
