<?php

/**
 * @file
 * Location Finder module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_theme().
 */
function location_finder_theme($existing, $type, $theme, $path) {
  return [
    'location_finder_element' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_entity_view_alter().
 */
function location_finder_entity_view_alter(&$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if (
    $entity->getEntityTypeID() != 'node' ||
    !in_array($entity->getType(), ['branch', 'camp', 'facility']) ||
    $display->getMode() != 'teaser'
  ) {
    return;
  }

  // Add attribute with location data.
  $tags = [];
  switch ($entity->getType()) {
    case 'branch':
      $tags[] = t('YMCA');
      break;

    case 'camp':
      $tags[] = t('Camps');
      break;

    case 'facility':
      $tags[] = t('Facilities');
      break;
  }
  $values = [
    'tags' => $tags,
  ];
  $build['#attributes']['data-locations'] = json_encode($values);

  $amenities = [];
  if ($entity->hasField('field_location_amenities')) {
    $entityAmenties = $entity->get('field_location_amenities')->getValue();
    foreach ($entityAmenties as $amenity) {
      $amenities[] = $amenity['target_id'];
    }
  }
  $build['#attributes']['data-amenities'] = json_encode($amenities);
}

/**
 * Implements hook_library_info_alter().
 */
function location_finder_library_info_alter(&$libraries, $extension) {
  if ($extension != 'location_finder') {
    return;
  }

  // Adding Google Maps API key.
  foreach ($libraries['location_finder']['js'] as $key => $value) {
    if ($key != 'https://maps.googleapis.com/maps/api/js') {
      continue;
    }
    $api_key = \Drupal::configFactory()->get('location_finder.settings')->get('google_map_api_key');
    unset($libraries['location_finder']['js'][$key]);
    $libraries['location_finder']['js'][$key . '?key=' . $api_key] = $value;
  }
}
