<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_create_access().
 */
function ymca_perms_entity_create_access(AccountInterface $account, array $context, $entity_bundle) {
  if ($context['entity_type_id'] == 'block_content') {
    if ($account->hasPermission('create custom blocks')) {
      return AccessResult::allowed();
    }
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function ymca_perms_menu_link_content_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($operation == 'view') {
    if ($account->hasPermission('insert menu links via entity embed')) {
      return AccessResult::allowed();
    }
  }

  return AccessResult::neutral();
}
