<?php

/**
 * @file
 * Contains openy_font.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\FileInterface;

/**
 * Implements hook_help().
 */
function openy_font_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the openy_font module.
    case 'help.page.openy_font':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OpenY Font settings module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Checks that the filename is allowed.
 *
 * @param \Drupal\file\FileInterface $file
 *   A file entity.
 * @param string $font_style
 *   A font style name.
 *
 * @return array
 *   An empty array if the file name is allowed or an array containing an
 *   error message if it's not.
 *
 * @see hook_file_validate()
 */
function openy_font_file_validation(FileInterface $file, $font_style) {
  $errors = [];

  $regex = '/.*' . preg_quote($font_style) . '.*$/i';
  if (!preg_match($regex, $file->getFilename())) {
    $errors[] = t("It looks like that you're trying to upload wrong font. Font name should contain %font_style in the name.", ['%font_style' => $font_style]);
  }
  else {
    $file->setPermanent();
    $file->save();
    /** @var \Drupal\file\FileUsage\DatabaseFileUsageBackend $file_usage */
    $file_usage = \Drupal::service('file.usage');
    $file_usage->add($file, 'openy_font', 'user', \Drupal::currentUser()->id());
  }
  return $errors;
}
