<?php

/**
 * @file
 * OpenY digital signage block html module.
 */

define('OPENY_DS_BLOCK_HTML_BUNDLE', 'digital_signage_block_free_html');

/**
 * Implements hook_theme_suggestions_block().
 */
function openy_digital_signage_block_html_theme_suggestions_block(array $variables) {
  if ($variables['elements']['#base_plugin_id'] != 'block_content') {
    return;
  }
  /* @var \Drupal\block_content\Entity\BlockContent $block */
  $block = $variables['elements']['content']['#block_content'];
  if ($block->bundle() != OPENY_DS_BLOCK_HTML_BUNDLE) {
    return;
  }
  // Add suggestion.
  $suggestions = [];
  $suggestions[] = 'block__' . $block->bundle();
  return $suggestions;
}

/**
 * Implements hook_preprocess_block() for block templates.
 */
function openy_digital_signage_block_html_preprocess_block(&$variables) {
  if ($variables['base_plugin_id'] != 'block_content') {
    return;
  }
  /* @var \Drupal\block_content\Entity\BlockContent $block */
  $block = $variables['content']['#block_content'];
  if ($block->bundle() != OPENY_DS_BLOCK_HTML_BUNDLE) {
    return;
  }
  // Do not display image.
  $variables['content']['field_ds_background_image']['#access'] = FALSE;
  $variables['background_image'] = '';
  if (!empty($variables['content']['field_ds_background_image'][0]['#file'])) {
    /* @var \Drupal\file_entity\Entity\FileEntity $file */
    $file = $variables['content']['field_ds_background_image'][0]['#file'];
    $variables['background_image'] = file_create_url($file->getFileUri());
  }
}

/**
 * Implements hook_block_content_view().
 */
function openy_digital_signage_block_html_block_content_view(array &$build, \Drupal\block_content\Entity\BlockContent $block_content, $view_mode) {
  if ($block_content->bundle() != OPENY_DS_BLOCK_HTML_BUNDLE) {
    return;
  }
  // Attach library with styles to block.
  $build['#attached']['library'][] = 'openy_digital_signage_block_html/block_html';
}

/**
 * Implements hook_theme().
 */
function openy_digital_signage_block_html_theme($existing, $type, $theme, $path) {
  return [
    'block__digital_signage_block_free_html' => [
      'template' => 'block--digital-signage-block-free-html',
      'render element' => 'elements',
      'base hook' => 'block',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function openy_digital_signage_block_html_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id != 'block_content_digital_signage_block_free_html_panels_ipe_form') {
    return;
  }
  $form['revision_information']['#access'] = FALSE;
}
