<?php

/**
 * @file
 * Module file.
 */

use Drupal\Component\Utility\Unicode;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Implements hook_theme().
 */
function ymca_blog_listing_theme($existing, $type, $theme, $path) {
  return [
    'ymca_news_events' => [
      'variables' => [
        'items' => NULL,
      ],
      'template' => 'ymca-news-events',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ymca_blog_listing_preprocess_node(&$variables) {
  // Add list News & Events items to camps and locations.
  $node = $variables['node'];
  $bundles = ['location', 'camp'];
  if (in_array($node->bundle(), $bundles)) {
    $items = [];
    $ids = [];

    try {
      // Day camp news have the highest priority.
      $query = \Drupal::entityQuery('node')
        ->condition('type', 'blog')
        ->condition('status', 1)
        ->condition('field_related_camps_locations.target_id', $node->id())
        ->sort('created', 'DESC')
        ->range(0, 2);
      $ids = $query->execute();

      // Extend the results with related posts.
      if (count($ids) < 2) {
        $query = \Drupal::entityQuery('node')
          ->condition('type', 'blog')
          ->condition('status', 1)
          ->condition('field_site_section.target_id', $node->id())
          ->sort('created', 'DESC')
          ->range(0, 2 - count($ids));
        $ids += $query->execute();
      }

      // Finally, extend by 1 or load 2 general Blog Posts if "Include General Blog Post" is checked.
      if (count($ids) < 2) {
        $field_include_name = 'field_include_general_blog_posts';
        if ($node->hasField($field_include_name)) {
          $field_include = $node->get($field_include_name);
          if (!$field_include->isEmpty()) {
            // Load all ids of Blog Post CT that are not related to any site section.
            $query = \Drupal::entityQuery('node')
              ->condition('type', 'blog')
              ->notExists('field_site_section')
              ->notExists('field_related_camps_locations')
              ->condition('status', 1)
              ->sort('created', 'DESC')
              ->range(0, 2 - count($ids));
            $ids += $query->execute();
          }
        }
      }

    }
    catch (Exception $e) {
      watchdog_exception('ymca_blog_listing', $e);
    }

    // Load nodes and build output array.
    $nodes = \Drupal::getContainer()->get('entity.manager')->getStorage('node')->loadMultiple($ids);

    foreach ($nodes as $nid => $n) {
      $node_url = Url::fromUri('entity:node/' . $nid);
      $items[] = [
        'title' => new Link($n->getTitle(), $node_url),
        'text' => Unicode::truncate($n->field_summary->value, 180, TRUE, FALSE),
        'read_more_url' => $node_url,
      ];
    }

    $variables['news_events'] = [
      '#theme' => 'ymca_news_events',
      '#items' => $items,
      '#cache' => [
        'tags' => Cache::mergeTags(
          ['node_list'],
          Cache::buildTags('node', $ids)
        )
      ]
    ];

  }
}
