<?php
/**
 * @file
 * Contains ymca_master specific functions
 */

use Drupal\Core\Config\InstallStorage;

function _ymca_master_import_config($filename) {
  $contents = @file_get_contents($filename);
  if (!$contents) {
    return;
  }
  $config_manager = \Drupal::service('config.manager');
  $data = (new InstallStorage())->decode($contents);
  $config_name = basename($filename, '.yml');
  $entity_type_id = $config_manager->getEntityTypeIdByName($config_name);
  if ($entity_type_id) {
    $entity_storage = $config_manager->getEntityManager()->getStorage($entity_type_id);
    $entity_id = $entity_storage::getIDFromConfigName($config_name, $entity_storage->getEntityType()->getConfigPrefix());
    $entity_type = $entity_storage->getEntityType();
    $id_key = $entity_type->getKey('id');
    $data[$id_key] = $entity_id;
    $entity = $entity_storage->create($data);
    if ($existing_entity = $entity_storage->load($entity_id)) {
      $entity
        ->set('uuid', $existing_entity->uuid())
        ->enforceIsNew(FALSE);
    }
    $entity_storage->save($entity);
  }
  else {
    $this->configFactory->getEditable($config_name)->setData($data)->save();
  }
}