<?php

/**
 * @file
 * Main module's file.
 */

/**
 * Deploy Program Event Framework related landing pages.
 */
function openy_demo_nlanding_pef_pages() {
  // Make sure that blocks are available.
  openy_enable_module('openy_repeat');
  drupal_flush_all_caches();

  /**
   * Get category ID by title.
   *
   * @param string $title
   *   Category title.
   *
   * @return mixed
   *   Category ID.
   */
  $get_activity_id_by_title = function ($title) {
    $query = \Drupal::entityQuery('node')
      ->condition('type', 'activity')
      ->condition('title', $title);
    return reset($query->execute());
  };

  $schedules_node = \Drupal\node\Entity\Node::create(
    [
      'type' => 'landing_page',
      'title' => 'Schedules',
      'langcode' => 'en',
      'uid' => '1',
      'status' => 1,
      'moderation_state' => 'published',
      'field_lp_layout' => ['value' => 'one_column_clean'],
    ]
  );
  $schedules_node->save();

  $locations_node = \Drupal\node\Entity\Node::create(
    [
      'type' => 'landing_page',
      'title' => 'Select location',
      'langcode' => 'en',
      'uid' => '1',
      'status' => 1,
      'moderation_state' => 'published',
      'field_lp_layout' => ['value' => 'one_column_clean'],
    ]
  );
  $locations_node->save();

  $group_exercises_nid = $get_activity_id_by_title('Group Exercise Classes');

  $schedules_paragraph = \Drupal\paragraphs\Entity\Paragraph::create(
    [
      'type' => 'repeat_schedules',
      'parent_id' => $schedules_node->id(),
      'parent_type' => 'node',
      'parent_field_name' => 'field_content',
      'status' => 1,
      'field_prgf_repeat_schedules_ref' => ['plugin_id' => 'repeat_schedules_block'],
      'field_prgf_repeat_schedules_pref' => ['target_id' => $locations_node->id()],
      'field_prgf_repeat_schedule_excl' => [
        [ 'target_id' => $group_exercises_nid ],
      ],
    ]
  );
  $schedules_paragraph->save();

  $schedules_node->field_content->entity = $schedules_paragraph;
  $schedules_node->save();

  $location_paragraph = \Drupal\paragraphs\Entity\Paragraph::create(
    [
      'type' => 'repeat_schedules_loc',
      'parent_id' => $locations_node->id(),
      'parent_type' => 'node',
      'parent_field_name' => 'field_content',
      'status' => 1,
      'field_prgf_block' => ['plugin_id' => 'repeat_schedules_loc_block'],
      'field_prgf_repeat_lschedules_prf' => ['target_id' => $schedules_node->id()],
    ]
  );
  $location_paragraph->save();

  $locations_node->field_content->entity = $location_paragraph;
  $locations_node->save();

  $parent_menu_link = \Drupal\menu_link_content\Entity\MenuLinkContent::load(39);
  $menu_link = \Drupal\menu_link_content\Entity\MenuLinkContent::create([
    'title' => 'Program Schedules',
    'link' => ['uri' => 'entity:node/' . $locations_node->id()],
    'menu_name' => 'main',
    'parent' => 'menu_link_content:' . $parent_menu_link->uuid(),
    'expanded' => TRUE,
  ]);
  $menu_link->save();

  $schedules_pages_to_create = [
    [
      'title' => 'Group Exercise Classes',
      'activity_id' => $get_activity_id_by_title('Group Exercise Classes'),
      'parent_menu_uuid' => $parent_menu_link->uuid(),
    ],
    [
      'title' => 'Programs & Activities',
      'activity_id' => $get_activity_id_by_title('Group Exercise Classes'),
      'parent_menu_uuid' => $parent_menu_link->uuid(),
    ],
    [
      'title' => 'Swim',
      'activity_id' => $get_activity_id_by_title('Group Exercise Classes'),
      'parent_menu_uuid' => $parent_menu_link->uuid(),
    ],
    [
      'title' => 'Personal Training',
      'activity_id' => $get_activity_id_by_title('Group Exercise Classes'),
      'parent_menu_uuid' => $parent_menu_link->uuid(),
    ],
    [
      'title' => 'Camp',
      'activity_id' => $get_activity_id_by_title('Group Exercise Classes'),
      'parent_menu_uuid' => $parent_menu_link->uuid(),
    ],
    [
      'title' => 'Kids & Teens',
      'activity_id' => $get_activity_id_by_title('Group Exercise Classes'),
      'parent_menu_uuid' => $parent_menu_link->uuid(),
    ],
  ];

  /**
   * Populate schedules pages.
   *
   * @param array $pages
   *   Array of pages.
   *
   * @throws \Exception
   */
  $pages_populate = function (array $pages) {
    foreach ($pages as $page) {
      // Create landing page.
      /** @var \Drupal\node\Entity\Node $node */
      $node = \Drupal\node\Entity\Node::create(
        [
          'type' => 'landing_page',
          'title' => $page['title'],
          'langcode' => 'en',
          'uid' => '1',
          'status' => 1,
          'moderation_state' => 'published',
          'field_lp_layout' => ['value' => 'one_column_clean'],
        ]
      );
      $node->save();

      $activity_id = $page['activity_id'];
      if (!$activity_id) {
        throw new \Exception(sprintf('Failed to get activity id for page "%s"', $page['title']));
      }

      // Create schedules paragraph.
      $paragraph = \Drupal\paragraphs\Entity\Paragraph::create(
        [
          'type' => 'repeat_schedules',
          'parent_id' => $node->id(),
          'parent_type' => 'node',
          'parent_field_name' => 'field_content',
          'status' => 1,
          'field_prgf_block' => ['plugin_id' => 'repeat_schedules_block'],
          'field_prgf_repeat_schedule_categ' => ['target_id' => $activity_id],
          'field_prgf_repeat_schedule_instr' => ['value' => TRUE],
        ]
      );
      $paragraph->save();

      // Update landing page with created paragraph.
      $node->field_content->entity = $paragraph;
      $node->save();

      // Create menu link.
      $menu_link = \Drupal\menu_link_content\Entity\MenuLinkContent::create([
        'title' => $page['title'],
        'link' => ['uri' => 'entity:node/' . $node->id()],
        'menu_name' => 'main',
        'parent' => 'menu_link_content:' . $page['parent_menu_uuid'],
        'expanded' => TRUE,
      ]);
      $menu_link->save();
    }
  };

  $pages_populate($schedules_pages_to_create);

  // For some reason repeat blocks do not have block's id in their
  // configuration. This is why we manually ensure they are set up.
  $process_paragraphs = function (array $tables, $plugin_id_field, $config_field) {
    foreach ($tables as $table) {
      // Select all paragraphs that have "broken" as plugin_id.
      $query = \Drupal::database()->select($table, 'ptable');
      $query->fields('ptable');
      $query->condition('ptable.' . $plugin_id_field, 'broken');
      $broken_paragraphs = $query->execute()->fetchAll();

      // Update to correct plugin_id based on data array.
      foreach ($broken_paragraphs as $paragraph) {
        $data = unserialize($paragraph->{$config_field});

        if ($paragraph->bundle == 'repeat_schedules') {
          $data['id'] = 'repeat_schedules_block';
        }
        elseif ($paragraph->bundle == 'repeat_schedules_loc') {
          $data['id'] = 'repeat_schedules_loc_block';
        }

        $query = \Drupal::database()->update($table);
        $query->fields([
          $plugin_id_field => $data['id'],
          $config_field => serialize($data),
        ]);
        $query->condition('bundle', $paragraph->bundle);
        $query->condition('entity_id', $paragraph->entity_id);
        $query->condition('revision_id', $paragraph->revision_id);
        $query->condition('langcode', $paragraph->langcode);
        $query->execute();
      }
    }
  };

  $process_paragraphs(
    [
      'paragraph__field_prgf_block',
      'paragraph_revision__field_prgf_block',
    ],
   'field_prgf_block_plugin_id',
   'field_prgf_block_plugin_configuration'
  );
}
