<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_batch_alter().
 */
function openy_prgf_global_nav_preprocess_html(&$variables) {
  /*$exclude = [
    'landing_page',
    'camp',
    'branch'
  ];

  if (!empty($variables['node_type']) && in_array($variables['node_type'], $exclude)) {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node->hasField('field_header_content') && $header = $node->field_header_content->getValue()) {
      foreach ($header as $p) {
        if ($paragraph = \Drupal::service('entity.manager')
          ->getStorage('paragraph')
          ->load($p['target_id'])
        ) {
          if ($paragraph->bundle() == 'global_nav') {
            unset($variables['page']['primary_menu']);
          }
        }
      }
    }
  }*/
}
