<?php

/**
 * Implements hook_openy_gxp_programs_csv_row_alter().
 */
function openy_gxp_example_openy_gxp_programs_csv_row_alter(&$row) {
  // Locations mapping. Ideally here should be mapping table of
  // gxp locations -> OpenY locations. Result should be id of the node.

  // For demo purposes use random location.
  static $locations;
  if (empty($locations)) {
    $query = \Drupal::entityQuery('node');
    $query->condition('status', 1);
    $query->condition('type', 'branch');
    $locations = array_values($query->execute());
  }

  $row['locations'] = $locations[rand(0, count($locations) - 1)];
}
