<?php

/**
 * @file
 * OpenY Node Landing module file.
 */

/**
 * Implements hook_field_group_form_process_alter().
 */
function openy_node_landing_field_group_form_process_alter(array &$element, &$group, &$complete_form) {
  if (!isset($element['#group_name']) || $element['#group_name'] !== 'group_sidebar_area' || !isset($element['#bundle']) || $element['#bundle'] != 'landing_page') {
    return;
  }
  // Set visible states for Landing page form Group Sidebar Area when Layout has
  // a two columns option selected.
  $element['#states'] = [
    'visible' => [
      [
        'select[name="field_lp_layout"]' => ['value' => 'two_column'],
      ],
      [
        'select[name="field_lp_layout"]' => ['value' => 'two_column_fixed'],
      ],
      [
        'select[name="field_lp_layout"]' => ['value' => 'two_column_left'],
      ],
    ],
  ];
}
