<?php

/**
 * @file
 * OpenY Node Landing module
 */

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_group_build_pre_render_alter().
 */
function openy_node_landing_field_group_build_pre_render_alter(&$element) {
  if (!isset($element['group_sidebar_area']) || !isset($element['group_sidebar_area']['#bundle']) || $element['group_sidebar_area']['#bundle'] != 'landing_page') {
    return;
  }
  // Set visible states for Landing page form Group Sidebar Area when Layout has
  // a two column option selected.
  $element['group_sidebar_area']['#states'] = [
    'visible' => [
      [
        'select[name="field_lp_layout"]' => ['value' => 'two_column'],
      ],
      [
        'select[name="field_lp_layout"]' => ['value' => 'two_column_fixed'],
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function openy_node_landing_form_node_landing_page_form_alter(&$form, FormStateInterface $form_state) {
  // Unset paragraph add options, by field, based on configuration.
  $fields_unset_paragraphs = Drupal::configFactory()->get('openy_node_landing.settings')
    ->get('fields_unset_paragraphs');
  foreach ($fields_unset_paragraphs as $field_name => $unset_paragraphs) {
    if (!isset($form[$field_name]) || empty($unset_paragraphs) || !is_array($unset_paragraphs)) {
      continue;
    }
    foreach ($unset_paragraphs as $unset_paragraph) {
      if (isset($form[$field_name]['widget']['add_more']['add_more_button_' . $unset_paragraph])) {
        unset($form[$field_name]['widget']['add_more']['add_more_button_' . $unset_paragraph]);
      }
    }
  }
}
