<?php

/**
 * Implements hook_theme().
 */
function openy_gtranslate_theme($existing, $type, $theme, $path) {
  return array(
    'openy_gtranslate' => [
      'variables' => [],
    ],
  );
}

/**
 * Implements hook_preprocess_block().
 */
function openy_gtranslate_preprocess_block(&$variables) {
  $blockType = $variables['elements']['#configuration']['provider'];

  if ($blockType == 'openy_gtranslate') {
    $variables['attributes']['class'][] = 'openy-gtranslate';
  }
}