<?php

namespace Drupal\openy_repeat\Controller;

use Drupal\Core\Controller\ControllerBase;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * {@inheritdoc}
 */
class RepeatController extends ControllerBase {

  protected $data = [
    [
      'id' => '4354',
      'name' => 'Private Interest List',
      'duration' => '60 min',
      'location' => 'New York',
      'instructor' => 'Ms. Erna Hoeger',
      'time' => '09:00',
    ],
    [
      'id' => '4355',
      'name' => 'Wade Living Wellness',
      'duration' => '30 min',
      'location' => 'Phoenix',
      'instructor' => 'Ms. Freda Schowalter DDS',
      'time' => '09:00',
    ],
    [
      'id' => '4375',
      'name' => 'Swim Team - Interest List',
      'duration' => '30 min',
      'location' => 'Dallas',
      'instructor' => 'Bridget Johns',
      'time' => '09:00',
    ],
    [
      'id' => '4634',
      'name' => 'Swim Team - Living Wellness',
      'duration' => '45 min',
      'location' => 'New York',
      'instructor' => 'Noemi Kihn',
      'time' => '09:00',
    ],
    [
      'id' => '4924',
      'name' => 'Swim Team - Living Wellness',
      'duration' => '90 min',
      'location' => 'Los Angeles',
      'instructor' => 'Miss Nettie Pouros',
      'time' => '09:00',
    ],
    [
      'id' => '4429',
      'name' => 'Active Y Interest List',
      'duration' => '30 min',
      'location' => 'San Diego',
      'instructor' => 'Prof. Kirstin Shields',
      'time' => '09:00',
    ],
    [
      'id' => '4971',
      'name' => 'Active Y Swim',
      'duration' => '90 min',
      'location' => 'Chicago',
      'instructor' => 'Mr. Alec Dickens',
      'time' => '09:00',
    ],
    [
      'id' => '4461',
      'name' => 'Private Camp',
      'duration' => '45 min',
      'location' => 'Los Angeles',
      'instructor' => 'Hayley Robel',
      'time' => '09:00',
    ],
    [
      'id' => '4737',
      'name' => 'Discovery Interest List',
      'duration' => '60 min',
      'location' => 'Chicago',
      'instructor' => 'Joannie McCullough',
      'time' => '09:00',
    ],
    [
      'id' => '4234',
      'name' => 'Active Y Camp',
      'duration' => '45 min',
      'location' => 'Chicago',
      'instructor' => 'Jackeline Bradtke',
      'time' => '09:00',
    ],
    [
      'id' => '4273',
      'name' => 'Private Camp',
      'duration' => '60 min',
      'location' => 'Phoenix',
      'instructor' => 'Madelyn Rempel Sr.',
      'time' => '09:00',
    ],
    [
      'id' => '4289',
      'name' => 'Swim Team - Yoga',
      'duration' => '60 min',
      'location' => 'Chicago',
      'instructor' => 'Dr. Ronny Botsford',
      'time' => '09:00',
    ],
    [
      'id' => '4568',
      'name' => 'Private Interest List',
      'duration' => '45 min',
      'location' => 'New York',
      'instructor' => 'Gina Ratke',
      'time' => '09:00',
    ],
    [
      'id' => '4573',
      'name' => 'Discovery Living Wellness',
      'duration' => '60 min',
      'location' => 'Phoenix',
      'instructor' => 'Angelo Rowe',
      'time' => '09:00',
    ],
    [
      'id' => '4841',
      'name' => 'Private Interest List',
      'duration' => '45 min',
      'location' => 'Los Angeles',
      'instructor' => 'Loma Fisher I',
      'time' => '09:00',
    ],
    [
      'id' => '4075',
      'name' => 'Private Living Wellness',
      'duration' => '90 min',
      'location' => 'Los Angeles',
      'instructor' => 'Dr. Alex Macejkovic',
      'time' => '09:00',
    ],
    [
      'id' => '4336',
      'name' => 'Discovery Camp',
      'duration' => '60 min',
      'location' => 'Chicago',
      'instructor' => 'Leann Halvorson III',
      'time' => '09:00',
    ],
    [
      'id' => '4593',
      'name' => 'Discovery Living Wellness',
      'duration' => '30 min',
      'location' => 'New York',
      'instructor' => 'Evert Murphy',
      'time' => '09:00',
    ],
    [
      'id' => '4855',
      'name' => 'Private Swim',
      'duration' => '30 min',
      'location' => 'Phoenix',
      'instructor' => 'Zachary Wilkinson I',
      'time' => '09:00',
    ],
    [
      'id' => '4105',
      'name' => 'Discovery Yoga',
      'duration' => '60 min',
      'location' => 'San Diego',
      'instructor' => 'Robbie Cole',
      'time' => '10:00',
    ],
    [
      'id' => '4908',
      'name' => 'Private Interest List',
      'duration' => '60 min',
      'location' => 'Chicago',
      'instructor' => 'Miss Delta Schaefer',
      'time' => '10:00',
    ],
    [
      'id' => '4911',
      'name' => 'Active Y Interest List',
      'duration' => '45 min',
      'location' => 'Dallas',
      'instructor' => 'Prof. Celestino Botsford',
      'time' => '10:00',
    ],
    [
      'id' => '4666',
      'name' => 'Private Living Wellness',
      'duration' => '30 min',
      'location' => 'Los Angeles',
      'instructor' => 'Dr. Alta Trantow',
      'time' => '10:00',
    ],
    [
      'id' => '4443',
      'name' => 'Active Y Swim',
      'duration' => '45 min',
      'location' => 'Los Angeles',
      'instructor' => 'Tessie Gutmann IV',
      'time' => '10:00',
    ],
    [
      'id' => '4965',
      'name' => 'Wade Swim',
      'duration' => '90 min',
      'location' => 'San Diego',
      'instructor' => 'Henri Hudson',
      'time' => '10:00',
    ],
    [
      'id' => '4198',
      'name' => 'Swim Team - Interest List',
      'duration' => '45 min',
      'location' => 'New York',
      'instructor' => 'Mr. Jordyn O\'Kon Sr.',
      'time' => '10:00',
    ],
    [
      'id' => '4976',
      'name' => 'Private Interest List',
      'duration' => '60 min',
      'location' => 'Phoenix',
      'instructor' => 'Eva Homenick',
      'time' => '10:00',
    ],
    [
      'id' => '4481',
      'name' => 'Wade Living Wellness',
      'duration' => '45 min',
      'location' => 'Los Angeles',
      'instructor' => 'Pearlie Morar MD',
      'time' => '10:00',
    ],
    [
      'id' => '4010',
      'name' => 'Discovery Camp',
      'duration' => '30 min',
      'location' => 'New York',
      'instructor' => 'Stephon Greenfelder',
      'time' => '10:00',
    ],
    [
      'id' => '4533',
      'name' => 'Private Living Wellness',
      'duration' => '90 min',
      'location' => 'Los Angeles',
      'instructor' => 'Isabel McKenzie',
      'time' => '10:00',
    ],
    [
      'id' => '4282',
      'name' => 'Active Y Swim',
      'duration' => '90 min',
      'location' => 'New York',
      'instructor' => 'Bo Roob',
      'time' => '10:00',
    ],
    [
      'id' => '4041',
      'name' => 'Wade Interest List',
      'duration' => '45 min',
      'location' => 'San Diego',
      'instructor' => 'Jimmie Fay',
      'time' => '10:00',
    ],
    [
      'id' => '4048',
      'name' => 'Swim Team - Yoga',
      'duration' => '90 min',
      'location' => 'Dallas',
      'instructor' => 'Helga Tremblay',
      'time' => '10:00',
    ],
    [
      'id' => '4344',
      'name' => 'Active Y Yoga',
      'duration' => '90 min',
      'location' => 'New York',
      'instructor' => 'Jackie Jacobs',
      'time' => '10:00',
    ],
    [
      'id' => '4600',
      'name' => 'Discovery Living Wellness',
      'duration' => '45 min',
      'location' => 'Los Angeles',
      'instructor' => 'Bernhard Gottlieb',
      'time' => '10:00',
    ],
    [
      'id' => '4874',
      'name' => 'Active Y Interest List',
      'duration' => '45 min',
      'location' => 'Los Angeles',
      'instructor' => 'Ms. Daniela Jakubowski I',
      'time' => '11:00',
    ],
    [
      'id' => '4644',
      'name' => 'Discovery Swim',
      'duration' => '90 min',
      'location' => 'San Diego',
      'instructor' => 'Aliza Vandervort',
      'time' => '11:00',
    ],
    [
      'id' => '4650',
      'name' => 'Discovery Interest List',
      'duration' => '60 min',
      'location' => 'Chicago',
      'instructor' => 'Cristobal Borer',
      'time' => '11:00',
    ],
    [
      'id' => '4655',
      'name' => 'Private Swim',
      'duration' => '90 min',
      'location' => 'Chicago',
      'instructor' => 'Jay Macejkovic',
      'time' => '11:00',
    ],
    [
      'id' => '4154',
      'name' => 'Wade Yoga',
      'duration' => '90 min',
      'location' => 'New York',
      'instructor' => 'Conner Nienow',
      'time' => '11:00',
    ],
    [
      'id' => '4675',
      'name' => 'Wade Interest List',
      'duration' => '90 min',
      'location' => 'Dallas',
      'instructor' => 'Stevie Pouros',
      'time' => '11:00',
    ],
    [
      'id' => '4167',
      'name' => 'Wade Camp',
      'duration' => '90 min',
      'location' => 'New York',
      'instructor' => 'Jett Dickinson',
      'time' => '11:00',
    ],
    [
      'id' => '4200',
      'name' => 'Swim Team - Yoga',
      'duration' => '45 min',
      'location' => 'San Diego',
      'instructor' => 'Roosevelt Cruickshank',
      'time' => '11:00',
    ],
    [
      'id' => '4714',
      'name' => 'Swim Team - Interest List',
      'duration' => '45 min',
      'location' => 'Los Angeles',
      'instructor' => 'Darron Lakin',
      'time' => '11:00',
    ],
    [
      'id' => '4730',
      'name' => 'Discovery Camp',
      'duration' => '60 min',
      'location' => 'New York',
      'instructor' => 'Myrna Stoltenberg Jr.',
      'time' => '11:00',
    ],
    [
      'id' => '4219',
      'name' => 'Wade Camp',
      'duration' => '30 min',
      'location' => 'Los Angeles',
      'instructor' => 'Tierra Hilll',
      'time' => '11:00',
    ],
    [
      'id' => '4239',
      'name' => 'Active Y Interest List',
      'duration' => '90 min',
      'location' => 'Chicago',
      'instructor' => 'Mr. Jovan Waelchi MD',
      'time' => '11:00',
    ],
    [
      'id' => '4265',
      'name' => 'Swim Team - Camp',
      'duration' => '45 min',
      'location' => 'New York',
      'instructor' => 'Frankie Abshire',
      'time' => '11:00',
    ],
    [
      'id' => '4294',
      'name' => 'Wade Yoga',
      'duration' => '45 min',
      'location' => 'San Diego',
      'instructor' => 'Cayla Gerlach',
      'time' => '11:00',
    ],
    [
      'id' => '4557',
      'name' => 'Discovery Camp',
      'duration' => '30 min',
      'location' => 'San Diego',
      'instructor' => 'Prof. Houston Hagenes II',
      'time' => '11:00',
    ],
    [
      'id' => '4394',
      'name' => 'Active Y Yoga',
      'duration' => '45 min',
      'location' => 'Dallas',
      'instructor' => 'Johan Bruen',
      'time' => '12:00',
    ],
    [
      'id' => '4907',
      'name' => 'Swim Team - Interest List',
      'duration' => '45 min',
      'location' => 'Dallas',
      'instructor' => 'Dr. Tracey Spencer',
      'time' => '12:00',
    ],
    [
      'id' => '4659',
      'name' => 'Private Swim',
      'duration' => '60 min',
      'location' => 'Dallas',
      'instructor' => 'Astrid Koelpin',
      'time' => '12:00',
    ],
    [
      'id' => '4414',
      'name' => 'Wade Yoga',
      'duration' => '60 min',
      'location' => 'Chicago',
      'instructor' => 'Lee Larson',
      'time' => '12:00',
    ],
    [
      'id' => '4418',
      'name' => 'Private Swim',
      'duration' => '45 min',
      'location' => 'New York',
      'instructor' => 'Florencio Renner',
      'time' => '12:00',
    ],
    [
      'id' => '4209',
      'name' => 'Active Y Swim',
      'duration' => '30 min',
      'location' => 'Dallas',
      'instructor' => 'Luigi Torphy',
      'time' => '12:00',
    ],
    [
      'id' => '4213',
      'name' => 'Discovery Interest List',
      'duration' => '45 min',
      'location' => 'New York',
      'instructor' => 'Alf Ernser MD',
      'time' => '12:00',
    ],
    [
      'id' => '4496',
      'name' => 'Private Living Wellness',
      'duration' => '45 min',
      'location' => 'Chicago',
      'instructor' => 'Angeline Schaden',
      'time' => '12:00',
    ],
    [
      'id' => '4759',
      'name' => 'Active Y Yoga',
      'duration' => '60 min',
      'location' => 'New York',
      'instructor' => 'Daisha Bechtelar',
      'time' => '12:00',
    ],
    [
      'id' => '4029',
      'name' => 'Wade Interest List',
      'duration' => '60 min',
      'location' => 'Phoenix',
      'instructor' => 'Monroe Dibbert',
      'time' => '12:00',
    ],
    [
      'id' => '4799',
      'name' => 'Active Y Living Wellness',
      'duration' => '60 min',
      'location' => 'Dallas',
      'instructor' => 'Marquis Ferry',
      'time' => '12:00',
    ],
    [
      'id' => '4806',
      'name' => 'Swim Team - Swim',
      'duration' => '90 min',
      'location' => 'San Diego',
      'instructor' => 'Justina Trantow',
      'time' => '12:00',
    ],
    [
      'id' => '4315',
      'name' => 'Wade Swim',
      'duration' => '90 min',
      'location' => 'Los Angeles',
      'instructor' => 'Dr. Lelah Sipes V',
      'time' => '12:00',
    ],
    [
      'id' => '4087',
      'name' => 'Private Living Wellness',
      'duration' => '45 min',
      'location' => 'New York',
      'instructor' => 'Aiyana Fadel',
      'time' => '12:00',
    ],
    [
      'id' => '4138',
      'name' => 'Active Y Swim',
      'duration' => '90 min',
      'location' => 'Phoenix',
      'instructor' => 'Jace Lebsack',
      'time' => '13:00',
    ],
    [
      'id' => '4952',
      'name' => 'Private Living Wellness',
      'duration' => '45 min',
      'location' => 'Dallas',
      'instructor' => 'Vergie Botsford Jr.',
      'time' => '13:00',
    ],
    [
      'id' => '4455',
      'name' => 'Wade Swim',
      'duration' => '60 min',
      'location' => 'Dallas',
      'instructor' => 'Elenora Hettinger',
      'time' => '13:00',
    ],
    [
      'id' => '4456',
      'name' => 'Discovery Living Wellness',
      'duration' => '30 min',
      'location' => 'Chicago',
      'instructor' => 'Era VonRueden',
      'time' => '13:00',
    ],
    [
      'id' => '4206',
      'name' => 'Wade Interest List',
      'duration' => '60 min',
      'location' => 'Chicago',
      'instructor' => 'Joanie Cormier',
      'time' => '13:00',
    ],
    [
      'id' => '4974',
      'name' => 'Active Y Interest List',
      'duration' => '90 min',
      'location' => 'San Diego',
      'instructor' => 'Forest Wolf',
      'time' => '13:00',
    ],
    [
      'id' => '4244',
      'name' => 'Private Living Wellness',
      'duration' => '30 min',
      'location' => 'Phoenix',
      'instructor' => 'Aaliyah Bradtke',
      'time' => '13:00',
    ],
    [
      'id' => '4266',
      'name' => 'Wade Camp',
      'duration' => '45 min',
      'location' => 'Chicago',
      'instructor' => 'Pattie Blanda',
      'time' => '13:00',
    ],
    [
      'id' => '4025',
      'name' => 'Private Camp',
      'duration' => '30 min',
      'location' => 'New York',
      'instructor' => 'Quinton Walker',
      'time' => '13:00',
    ],
    [
      'id' => '4579',
      'name' => 'Wade Interest List',
      'duration' => '60 min',
      'location' => 'Los Angeles',
      'instructor' => 'Jana Erdman',
      'time' => '13:00',
    ],
    [
      'id' => '4859',
      'name' => 'Active Y Camp',
      'duration' => '45 min',
      'location' => 'Chicago',
      'instructor' => 'Sandrine Jacobson',
      'time' => '13:00',
    ],
    [
      'id' => '4860',
      'name' => 'Wade Camp',
      'duration' => '90 min',
      'location' => 'Los Angeles',
      'instructor' => 'Janiya Emard',
      'time' => '13:00',
    ],
    [
      'id' => '4865',
      'name' => 'Active Y Interest List',
      'duration' => '60 min',
      'location' => 'Dallas',
      'instructor' => 'Dr. Doug Yundt V',
      'time' => '14:00',
    ],
    [
      'id' => '4646',
      'name' => 'Discovery Swim',
      'duration' => '60 min',
      'location' => 'Chicago',
      'instructor' => 'Mrs. Shanny Pouros II',
      'time' => '14:00',
    ],
    [
      'id' => '4402',
      'name' => 'Active Y Yoga',
      'duration' => '45 min',
      'location' => 'San Diego',
      'instructor' => 'Jaylon Ferry',
      'time' => '14:00',
    ],
    [
      'id' => '4943',
      'name' => 'Wade Interest List',
      'duration' => '60 min',
      'location' => 'Chicago',
      'instructor' => 'Marie Bruen',
      'time' => '14:00',
    ],
    [
      'id' => '4433',
      'name' => 'Private Interest List',
      'duration' => '90 min',
      'location' => 'New York',
      'instructor' => 'Shania Orn Sr.',
      'time' => '14:00',
    ],
    [
      'id' => '4723',
      'name' => 'Wade Camp',
      'duration' => '30 min',
      'location' => 'San Diego',
      'instructor' => 'Mrs. Tomasa Bins II',
      'time' => '14:00',
    ],
    [
      'id' => '4993',
      'name' => 'Wade Swim',
      'duration' => '90 min',
      'location' => 'Phoenix',
      'instructor' => 'Dr. Laverne Spencer MD',
      'time' => '14:00',
    ],
    [
      'id' => '4488',
      'name' => 'Active Y Living Wellness',
      'duration' => '45 min',
      'location' => 'Chicago',
      'instructor' => 'Lawson Moen',
      'time' => '14:00',
    ],
    [
      'id' => '4251',
      'name' => 'Private Swim',
      'duration' => '45 min',
      'location' => 'New York',
      'instructor' => 'Mrs. Keira Flatley',
      'time' => '14:00',
    ],
    [
      'id' => '4258',
      'name' => 'Swim Team - Interest List',
      'duration' => '90 min',
      'location' => 'Phoenix',
      'instructor' => 'Elias Marvin',
      'time' => '14:00',
    ],
    [
      'id' => '4016',
      'name' => 'Active Y Interest List',
      'duration' => '90 min',
      'location' => 'Chicago',
      'instructor' => 'Kaylin Sipes',
      'time' => '14:00',
    ],
    [
      'id' => '4032',
      'name' => 'Private Yoga',
      'duration' => '60 min',
      'location' => 'New York',
      'instructor' => 'Austin Quitzon',
      'time' => '14:00',
    ],
    [
      'id' => '4307',
      'name' => 'Private Living Wellness',
      'duration' => '60 min',
      'location' => 'Phoenix',
      'instructor' => 'Laurine Sawayn',
      'time' => '14:00',
    ],
    [
      'id' => '4824',
      'name' => 'Discovery Camp',
      'duration' => '45 min',
      'location' => 'Phoenix',
      'instructor' => 'Mrs. Hilda Schmidt',
      'time' => '14:00',
    ],
    [
      'id' => '4318',
      'name' => 'Swim Team - Camp',
      'duration' => '90 min',
      'location' => 'New York',
      'instructor' => 'Jennyfer Metz',
      'time' => '14:00',
    ],
    [
      'id' => '4832',
      'name' => 'Swim Team - Swim',
      'duration' => '60 min',
      'location' => 'New York',
      'instructor' => 'Mr. Mckenna Hintz',
      'time' => '14:00',
    ],
    [
      'id' => '4331',
      'name' => 'Active Y Swim',
      'duration' => '90 min',
      'location' => 'New York',
      'instructor' => 'Prof. Elinore Nolan',
      'time' => '14:00',
    ],
    [
      'id' => '4618',
      'name' => 'Active Y Interest List',
      'duration' => '30 min',
      'location' => 'Chicago',
      'instructor' => 'Rasheed Bechtelar',
      'time' => '15:00',
    ],
    [
      'id' => '4890',
      'name' => 'Discovery Interest List',
      'duration' => '60 min',
      'location' => 'San Diego',
      'instructor' => 'Mr. Judson Schulist',
      'time' => '15:00',
    ],
    [
      'id' => '4642',
      'name' => 'Discovery Living Wellness',
      'duration' => '30 min',
      'location' => 'Phoenix',
      'instructor' => 'Prof. Faustino Kohler',
      'time' => '15:00',
    ],
    [
      'id' => '4400',
      'name' => 'Wade Camp',
      'duration' => '60 min',
      'location' => 'Los Angeles',
      'instructor' => 'Prof. Herbert Kuhn',
      'time' => '15:00',
    ],
    [
      'id' => '4920',
      'name' => 'Swim Team - Swim',
      'duration' => '45 min',
      'location' => 'New York',
      'instructor' => 'Emilia Kohler III',
      'time' => '15:00',
    ],
    [
      'id' => '4944',
      'name' => 'Swim Team - Camp',
      'duration' => '30 min',
      'location' => 'Dallas',
      'instructor' => 'Rashad Herzog',
      'time' => '15:00',
    ],
    [
      'id' => '4185',
      'name' => 'Wade Swim',
      'duration' => '60 min',
      'location' => 'Los Angeles',
      'instructor' => 'Thora Littel',
      'time' => '15:00',
    ],
    [
      'id' => '4190',
      'name' => 'Private Living Wellness',
      'duration' => '45 min',
      'location' => 'New York',
      'instructor' => 'Suzanne Buckridge PhD',
      'time' => '15:00',
    ],
    [
      'id' => '4479',
      'name' => 'Swim Team - Swim',
      'duration' => '30 min',
      'location' => 'San Diego',
      'instructor' => 'Miss Chasity Harvey',
      'time' => '15:00',
    ],
    [
      'id' => '4256',
      'name' => 'Active Y Swim',
      'duration' => '45 min',
      'location' => 'Dallas',
      'instructor' => 'Rhea Weimann',
      'time' => '15:00',
    ],
    [
      'id' => '4807',
      'name' => 'Swim Team - Living Wellness',
      'duration' => '45 min',
      'location' => 'Los Angeles',
      'instructor' => 'Billie Osinski',
      'time' => '15:00',
    ],
    [
      'id' => '4555',
      'name' => 'Private Camp',
      'duration' => '90 min',
      'location' => 'Chicago',
      'instructor' => 'Haylee Mills',
      'time' => '15:00',
    ],
    [
      'id' => '4814',
      'name' => 'Wade Living Wellness',
      'duration' => '30 min',
      'location' => 'Phoenix',
      'instructor' => 'Mr. Arlo Morissette II',
      'time' => '15:00',
    ],
    [
      'id' => '4576',
      'name' => 'Discovery Camp',
      'duration' => '45 min',
      'location' => 'Los Angeles',
      'instructor' => 'Bette Ziemann',
      'time' => '15:00',
    ],
    [
      'id' => '4362',
      'name' => 'Discovery Living Wellness',
      'duration' => '45 min',
      'location' => 'New York',
      'instructor' => 'Marty Buckridge',
      'time' => '16:00',
    ],
    [
      'id' => '4131',
      'name' => 'Wade Yoga',
      'duration' => '90 min',
      'location' => 'New York',
      'instructor' => 'Emmanuelle Lebsack',
      'time' => '16:00',
    ],
    [
      'id' => '4657',
      'name' => 'Discovery Swim',
      'duration' => '30 min',
      'location' => 'San Diego',
      'instructor' => 'Elta Bins',
      'time' => '16:00',
    ],
    [
      'id' => '4404',
      'name' => 'Active Y Swim',
      'duration' => '30 min',
      'location' => 'Phoenix',
      'instructor' => 'Pearl O\'Hara Sr.',
      'time' => '16:00',
    ],
    [
      'id' => '4156',
      'name' => 'Wade Camp',
      'duration' => '60 min',
      'location' => 'Dallas',
      'instructor' => 'Mr. Douglas Dickinson',
      'time' => '16:00',
    ],
    [
      'id' => '4673',
      'name' => 'Discovery Yoga',
      'duration' => '45 min',
      'location' => 'Los Angeles',
      'instructor' => 'Prof. Davin Buckridge Sr.',
      'time' => '16:00',
    ],
    [
      'id' => '4930',
      'name' => 'Swim Team - Living Wellness',
      'duration' => '45 min',
      'location' => 'Chicago',
      'instructor' => 'Ms. Lia Miller',
      'time' => '16:00',
    ],
    [
      'id' => '4953',
      'name' => 'Private Camp',
      'duration' => '45 min',
      'location' => 'Los Angeles',
      'instructor' => 'Jarrod Halvorson',
      'time' => '16:00',
    ],
    [
      'id' => '4189',
      'name' => 'Swim Team - Interest List',
      'duration' => '90 min',
      'location' => 'New York',
      'instructor' => 'Delfina Ortiz',
      'time' => '16:00',
    ],
    [
      'id' => '4475',
      'name' => 'Discovery Swim',
      'duration' => '60 min',
      'location' => 'New York',
      'instructor' => 'Marcia Bayer',
      'time' => '16:00',
    ],
    [
      'id' => '4492',
      'name' => 'Active Y Swim',
      'duration' => '90 min',
      'location' => 'San Diego',
      'instructor' => 'Lorna Marquardt Sr.',
      'time' => '16:00',
    ],
    [
      'id' => '4249',
      'name' => 'Wade Interest List',
      'duration' => '45 min',
      'location' => 'Chicago',
      'instructor' => 'Ashlynn Hackett',
      'time' => '16:00',
    ],
    [
      'id' => '4519',
      'name' => 'Swim Team - Interest List',
      'duration' => '30 min',
      'location' => 'New York',
      'instructor' => 'Dr. Lennie Brakus II',
      'time' => '16:00',
    ],
    [
      'id' => '4303',
      'name' => 'Swim Team - Swim',
      'duration' => '45 min',
      'location' => 'Phoenix',
      'instructor' => 'Norene Mante',
      'time' => '16:00',
    ],
    [
      'id' => '4565',
      'name' => 'Private Yoga',
      'duration' => '30 min',
      'location' => 'Chicago',
      'instructor' => 'Dean DuBuque',
      'time' => '16:00',
    ],
    [
      'id' => '4312',
      'name' => 'Private Camp',
      'duration' => '60 min',
      'location' => 'New York',
      'instructor' => 'Prof. Janelle Gaylord DDS',
      'time' => '16:00',
    ],
    [
      'id' => '4572',
      'name' => 'Wade Yoga',
      'duration' => '90 min',
      'location' => 'San Diego',
      'instructor' => 'Cary Mueller',
      'time' => '16:00',
    ],
    [
      'id' => '4575',
      'name' => 'Discovery Camp',
      'duration' => '45 min',
      'location' => 'Los Angeles',
      'instructor' => 'Fred Hoeger',
      'time' => '16:00',
    ],
    [
      'id' => '4838',
      'name' => 'Active Y Yoga',
      'duration' => '90 min',
      'location' => 'San Diego',
      'instructor' => 'Aurelio Harvey',
      'time' => '16:00',
    ],
    [
      'id' => '4098',
      'name' => 'Wade Interest List',
      'duration' => '45 min',
      'location' => 'Dallas',
      'instructor' => 'Nicolette Koss',
      'time' => '17:00',
    ],
    [
      'id' => '4112',
      'name' => 'Wade Yoga',
      'duration' => '90 min',
      'location' => 'Phoenix',
      'instructor' => 'Domingo O\'Connell',
      'time' => '17:00',
    ],
    [
      'id' => '4369',
      'name' => 'Active Y Living Wellness',
      'duration' => '30 min',
      'location' => 'Chicago',
      'instructor' => 'Mariah Schuppe',
      'time' => '17:00',
    ],
    [
      'id' => '4893',
      'name' => 'Swim Team - Swim',
      'duration' => '90 min',
      'location' => 'Los Angeles',
      'instructor' => 'Nayeli Wilkinson',
      'time' => '17:00',
    ],
    [
      'id' => '4927',
      'name' => 'Discovery Interest List',
      'duration' => '30 min',
      'location' => 'Los Angeles',
      'instructor' => 'Jaycee Kertzmann',
      'time' => '17:00',
    ],
    [
      'id' => '4420',
      'name' => 'Active Y Living Wellness',
      'duration' => '90 min',
      'location' => 'San Diego',
      'instructor' => 'Oswald Klein',
      'time' => '17:00',
    ],
    [
      'id' => '4739',
      'name' => 'Wade Interest List',
      'duration' => '90 min',
      'location' => 'San Diego',
      'instructor' => 'Joaquin Schaefer',
      'time' => '17:00',
    ],
    [
      'id' => '4525',
      'name' => 'Swim Team - Yoga',
      'duration' => '30 min',
      'location' => 'Chicago',
      'instructor' => 'Prof. Lelah Hudson IV',
      'time' => '17:00',
    ],
    [
      'id' => '4271',
      'name' => 'Swim Team - Camp',
      'duration' => '60 min',
      'location' => 'Phoenix',
      'instructor' => 'Mrs. Bette Kozey II',
      'time' => '17:00',
    ],
    [
      'id' => '4804',
      'name' => 'Wade Living Wellness',
      'duration' => '45 min',
      'location' => 'San Diego',
      'instructor' => 'Margarette Gutkowski III',
      'time' => '17:00',
    ],
    [
      'id' => '4037',
      'name' => 'Discovery Yoga',
      'duration' => '30 min',
      'location' => 'San Diego',
      'instructor' => 'Jolie Lowe',
      'time' => '17:00',
    ],
    [
      'id' => '4074',
      'name' => 'Wade Swim',
      'duration' => '30 min',
      'location' => 'Los Angeles',
      'instructor' => 'Dr. Dax Zieme',
      'time' => '17:00',
    ],
    [
      'id' => '4335',
      'name' => 'Active Y Swim',
      'duration' => '45 min',
      'location' => 'New York',
      'instructor' => 'Reese Pfeffer',
      'time' => '17:00',
    ],
    [
      'id' => '4592',
      'name' => 'Swim Team - Interest List',
      'duration' => '90 min',
      'location' => 'Dallas',
      'instructor' => 'Monserrat Veum',
      'time' => '17:00',
    ],
    [
      'id' => '4339',
      'name' => 'Active Y Interest List',
      'duration' => '45 min',
      'location' => 'San Diego',
      'instructor' => 'Mariana Flatley DDS',
      'time' => '17:00',
    ],
    [
      'id' => '4343',
      'name' => 'Active Y Yoga',
      'duration' => '90 min',
      'location' => 'San Diego',
      'instructor' => 'Jaime Brakus',
      'time' => '17:00',
    ],
  ];

  /**
   * {@inheritdoc}
   */
  public function dashboard() {
    return [
      '#theme' => 'openy_repeat_schedule_dashboard',
      '#current_date' => date('d Y'),
      // @todo change in future for real locations.
      '#locations' => $this->getLocations(),//['New York', 'Texas', 'Boston', 'Dallas'],
    ];
  }


  public function ajaxScheduler( Request $request, string $location, string $date ) {
    if (!empty($location)) {
      $location = explode(',', $location);
      $response = array_filter($this->data, function ($ev) use ($location, $date) {
        return in_array("'{$ev['location']}'", $location) ? TRUE : FALSE;
      });
    }
    else {
      $response = $this->data;
    }

    return  new JsonResponse( $response );
  }

  public function getLocations() {
    $locations = [];
    array_walk($this->data, function($ev) use (&$locations) {
      if (!in_array($ev['location'], $locations)) {
        $locations[] = $ev['location'];
      }
    });
    return  $locations;//new JsonResponse( $locations );
  }

}
