<?php

/**
 * @file
 * Contains ymca_head_attachments.module.
 */

use Drupal\Core\Url;

/**
* Implements hook_page_attachments().
*/
function ymca_head_attachments_page_attachments(array &$page) {
  $route_match = \Drupal::routeMatch();
  if ($route_match->getRouteName() == 'entity.node.canonical') {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node->bundle() == 'location') {
      $url = Url::fromRouteMatch($route_match);
      $url->setOption('absolute', TRUE);
      $address = $node->field_location->address_line1;
      $address = explode(', ', $address);
      $target_id = $node->field_working_hours->target_id;
      $working_hours_block = \Drupal::service('entity.manager')->getStorage('block_content')->load($target_id);
      $facility_hours = $working_hours_block->field_facility_hours->getValue();
      $days_mapping = [
        'hours_mon' => 'Monday',
        'hours_tue' => 'Tuesday',
        'hours_wed' => 'Wednesday',
        'hours_thu' => 'Thursday',
        'hours_fri' => 'Friday',
        'hours_sat' => 'Saturday',
        'hours_sun' => 'Sunday',
      ];
      $hours = '';
      if (!empty($facility_hours[0])) {
        foreach ($facility_hours[0] as $key => $day) {
          $hours[] = '"' . $days_mapping[$key] . ' ' . $day . '"';
        }
        $hours = implode(', ', $hours);
      }
      $data = [
        'url' => $url->toString(),
        'address' => [
          'locality' => $address[1],
          'region' => $address[2],
          'postal_code' => $node->field_location->postal_code,
          'street' => $address[0],
        ],
        'name' => $node->getTitle(),
        'tel' => $node->field_phone->value,
        'hours' => $hours,
      ];
      $local_business_schema = '{
        "@context": "http://schema.org",
        "@type": "ExerciseGym",
        "mainEntityOfPage": {
          "@type": "WebPage",
          "@id": "'. $data['url'] . '"
        },
        "address": {
          "@type": "PostalAddress",
          "addressLocality": "'. $data['address']['locality'] . 'Minneapolis",
          "addressRegion": "'. $data['address']['region'] . 'MN",
          "postalCode": "'. $data['address']['postal_code'] . '55402",
          "streetAddress": "'. $data['address']['street'] . '30 South 9th Street"
        },
        "name": "YMCA – '. $data['name'] . '",
        "openingHours": [' . $hours . '],
        "telephone": "'. $data['tel'] . '(612) 371-9622",
        "url": "'. $data['url'] . '"
      }';
      $script = [
        [
          '#type' => 'html_tag',
          '#tag' => 'script',
          '#value' => $local_business_schema,
          '#attributes' => array('type' => 'application/ld+json'),
        ],
        'local-business-schema',
      ];
      $page['#attached']['html_head'][] = [$script, 'canonical'];
    }
  }
}
