<?php

/**
 * Menu load callback; load a custom sitemap link from the {xmlsitemap} table.
 *
 * @param $id
 *   The sitemap link ID of the custom link to load.
 *
 * @see \Drupal\xmlsitemap\XmlSitemapLinkStorageInterface::load()
 */
function xmlsitemap_custom_load($id) {
  return \Drupal::service('xmlsitemap.link_storage')->load('custom', $id);
}

/**
 * Implements hook_xmlsitemap_link_info().
 */
function xmlsitemap_custom_xmlsitemap_link_info() {
  return array(
    'custom' => array(
      'label' => t('Custom links'),
    ),
  );
}
