<?php

/**
 * Implements hook_cron().
 */
function openy_analytics_cron() {
  // Check if cron was run less then 1 hrs ago and not at 2 AM.
  $periodicity = 604800;
  $lastRun = \Drupal::state()->get('openy_analytics.cron_visits_last_run', 0);
  $current = new \DateTime();
  $currentHour = $current->format('H');
  if ((\Drupal::time()->getRequestTime() - $lastRun) < $periodicity) {
    return FALSE;
  }

  $analytics_cron_service = \Drupal::getContainer()->get('analytics_cron');
  $analytics_cron_service->runCronServices();

  // Update last run.
  \Drupal::state()->set('openy_analytics.cron_visits_last_run', \Drupal::time()->getRequestTime());
}
