<?php

/**
 * @file
 * OpenY Camp module file.
 */

use Drupal\openy_loc_camp\CampHelper;

/**
 * Implements hook_theme_suggestions_page_alter
 */
function openy_loc_camp_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  // Add content type suggestion for Landing pages related to a camp.
  if ($node = \Drupal::request()->attributes->get('node')) {
    $node_type = $node->getType();
    if ($node_type = 'landing_page') {
      $camp = CampHelper::getLandingPageCampNode($node);
      if ($camp !== NULL) {
        $page__node__type_pos = array_search($page__node__type, $suggestions);
        $page__node__type__has_camp = 'page__node__' . $node_type . '__has_camp';
        array_splice($suggestions, $page__node__type_pos + 1, 0, $page__node__type__has_camp);
      }
    }
  }
}
