<?php

/**
 * @file
 * Open Y Camp module file.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function openy_loc_camp_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  // Add content type suggestion for Landing pages related to a camp.

  // Exit if not a node page, or if the 'openy_loc_camp.camp_service' is not available.
  if (!($node = \Drupal::request()->attributes->get('node')) || !($camp_service = \Drupal::service('openy_loc_camp.camp_service'))) {
    return;
  }

  // Exit if node type is not landing_page or if not related to a camp.
  if (!$node instanceof NodeInterface || ($node_type = $node->getType()) != 'landing_page' || !$camp_service->nodeHasOrIsCamp($node)) {
    return;
  }

  $page__node__type = 'page__node__' . $node_type;
  $page__node__type_pos = array_search($page__node__type, $suggestions);
  $page__node__type__has_camp = $page__node__type . '__has_camp';
  array_splice($suggestions, $page__node__type_pos + 1, 0, $page__node__type__has_camp);
}
