<?php

/**
 * @file
 * Module file for page_example_module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

const LNDR_BASE = 'https://lndr.co/';
const LNDR_API_GET_PROJECT = 'https://lndr.co/v1/projects';
const LNDR_API_VALIDATE_TOKEN = 'https://lndr.co/v1/validate_token';

/**
 * Implements hook_help().
 *
 */
function lndr_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'lndr.admin_settings':
      return t('Please refer to the <a href=":lndr-help">Lndr help page</a> on how to use this module', [':lndr-help' => base_path() . '/admin/help/lndr']);
    case 'help.page.lndr':
      $output = '';
      $output .= '<h3>' . t('About Lndr') . '</h3>';
      $output .= '<p>' . t('This module allows you to publish Lndr landing pages to Drupal 8 websites, for more information, please go to <a href=":lndr-home">https://lndr.co</a>.', [':lndr-home' => 'https://lndr.co']) . '</p>';
      $output .= '<h3>' . t('Before you start') . '</h3>';
      $output .= '<p>' . t('You will need a Lndr user account which you can obtain from https://lndr.co') . '</p>';
      $output .= '<h3>' . t('How to use the module') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Configuring the module') . '</dt>';
      $output .= '<dd>' . t('You can find the configuration page for Lndr under Administration > Configuration > Content authoring or <a href=":lndr">Lndr configuration page</a>.', [':lndr' => \Drupal::url('lndr.admin_settings')]) . '</dd>';
      $output .= '<dd>' . t('You can find the API token for Lndr under your <a href=":lndr-user">user profile in Lndr</a>.', [':lndr-user' => 'https://lndr.co/users/edit']) . '</dd>';
      $output .= '<dt>' . t('Using the module') . '</dt>';
      $output .= '<dd>' . t('Generally, you do not need to actively use this module once it has been successfully configured. There might be some exceptions such as changing the API token.') . '</dd>';
      $output .= '<dd>' . t('If your landing page created for Drupal does not show up, you can always run the Drupal cron manually to trigger the page sync.') . '</dd>';
      $output .= '<dd>' . t('Your landing page created for Drupal can be found under the <a href=":url-alias">URL alias</a> section', [':url-alias' => \Drupal::url('path.admin_overview')]) . '</dd>';
      $output .= '<dd>' . t('Lndr pages in Drupal will appear in the URL alias as /lndr/[id]') . '</dd>';
      $output .= '</dl>';
      $output .= '<p>' . t('For more information, contact <a href=":lndr-support">support@lndr.co</a>', [':lndr-support' => 'mailto:support@lndr.co']) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_cron().
 *
 */
function lndr_cron() {
  $controller = new \Drupal\lndr\Controller\LndrController();
  $controller->sync_path();
}
