<?php

/**
 * @file
 * Contains hook implementations.
 */

/**
 * Implements hook_views_data_alter().
 */
function verf_views_data_alter(array &$data) {
  $field_config_storage = \Drupal::entityTypeManager()->getStorage('field_config');
  /** @var \Drupal\field\FieldConfigInterface[] $field_configs */
  $field_configs = $field_config_storage->loadByProperties([
    'field_type' => 'entity_reference',
  ]);
  foreach ($field_configs as $field_config) {
    $table_name = $field_config->getTargetEntityTypeId() . '__' . $field_config->getName();
    $column_name = $field_config->getName() . '_target_id';
    if (isset($data[$table_name][$column_name])) {
      $data[$table_name][$column_name . '_verf'] = [
        'title' => t('@label (VERF selector)', [
          '@label' => $field_config->label(),
        ]),
        'group' => $data[$table_name][$column_name]['group'],
        'help' => $data[$table_name][$column_name]['help'],
        'filter' => [
          'field' => $column_name,
          'table' => $table_name,
          'id' => 'verf',
          'additional fields' => [],
          'field_name' => $field_config->getName(),
          'entity_type' => $field_config->getTargetEntityTypeId(),
          'verf_target_entity_type_id' => $field_config->getSetting('target_type'),
          'allow empty' => TRUE,
        ],
      ];
    }
  }
}