<?php

/**
 * @file
 * Install, update and uninstall functions for the openy_prgf_mc feature.
 */

/**
 * Update field_prgf_mc field form settings .
 */
function openy_prgf_mc_8001() {
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory(drupal_get_path('module', 'openy_prgf_mc') . '/config/install');
  $config_importer->importConfigs(
    [
      'core.entity_form_display.paragraph.membership_calculator.default',
    ]
  );
}
