<?php

/**
 * @file
 * Exposes global functionality for video fields.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity\File;
use Drupal\field\FieldStorageConfigInterface;
use Drupal\field\FieldConfigInterface;

/**
 * Implements hook_theme().
 */
function video_theme() {
  return array(
    'video_player_formatter' => array(
      'variables' => array('items' => NULL, 'player_attributes' => NULL)
    ),
  );
}