<?php

use Drupal\openy_block_date\EntityOperations;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * @file
 * Contains date block module file.
 */

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function openy_block_date_block_content_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->bundle() == 'date_block') {
    $build = \Drupal::service('class_resolver')
      ->getInstanceFromDefinition(EntityOperations::class)
      ->viewAlter($build, $entity, $display);
  }
}
