<?php

/**
 * @file
 * Contains ymca_camp_du_nord.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ymca_camp_du_nord_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ymca_camp_du_nord module.
    case 'help.page.ymca_camp_du_nord':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('YMCA Camp du Nord base module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ymca_camp_du_nord_theme($existing, $type, $theme, $path) {
  return [
    'cdn_results_wrapper' => [
      'variables' => [
        'teasers' => [],
      ],
      'template' => 'cdn-results-wrapper',
    ],
    'cdn_village_teaser' => [
      'variables' => [
        'title' => '',
        'image' => '',
        'availability' => '',
        'capacity' => '',
      ],
      'template' => 'cdn-village-teaser',
    ],
  ];
}

/**
 * Helper function to make results layout.
 *
 * @param array $cdn_products
 *   Fetched products.
 *
 * @return array
 *   Results render array.
 */
function ymca_camp_du_nord_results_layout(array $cdn_products) {
  $results = $teasers = [];
  $cache = [
    'max-age' => 3600,
    'contexts' => ['url.query_args'],
  ];
  $default_availability = t('Available');
  if (!empty($cdn_products)) {
    foreach ($cdn_products as $product) {
      $teasers[] = [
        '#theme' => 'cdn_village_teaser',
        '#title' => !empty($product->getName()) ? substr($product->getName(), 9) : '',
        '#image' => drupal_get_path('module', 'ymca_camp_du_nord') . '/assets/cabin' . rand(1, 3) . '.png',
        '#availability' => $default_availability,
        '#capacity' => rand(2, 14),
        '#cache' => $cache,
      ];
    }
    $results = [
      '#theme' => 'cdn_results_wrapper',
      '#teasers' => $teasers,
      '#cache' => $cache,
    ];
  }

  return $results;
}
