<?php

/**
 * @file
 * Contains ymca_camp_du_nord.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ymca_camp_du_nord_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ymca_camp_du_nord module.
    case 'help.page.ymca_camp_du_nord':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('YMCA Camp du Nord base module.') . '</p>';
      return $output;

    default:
  }
}
